kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  # storageClassName: nfs-client
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
