kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb
  namespace: dugulan-com
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
