---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: wordpress
  namespace: dugulan-com
spec:
  encryptedData:
    WORDPRESS_DATABASE_PASSWORD: AgBs57zN/eg1yDnSXVikZ9cP8r4fPUCHRQ2b/VGcj+zaio/tRhEMJMvyS37iwOpXyLMKxdyDNdAdLTbOqAfR7tPRzDoENLgptF0R4ubezSM2DuXFpjRx1+ZiN4EKApYin/vZuBxAGRA090kp21kkdxvZ7Od+IZiRsuiu68oTThPclPp/WYHfHK/ZnH2CLZoXURtSHyHiS6SxE7q4r5ZSCiwRwzO2vTse/w4xit1MzTMUqzGB6vf2Qmv/dH41GRZODvO1yL8+QBOthOsrrGfh3sHGx+xVvjY6FaO1pi3cjfG6rgXF8WHXWV92VdYu3SFY14Mb/ph9BNgf7Pa8WwNJOmAL0t7wLWVcfiGd5OpSDvIbYFNtqXDTrFJmKsR556OOLp5A70FgmbS7O6mH16N3b8sQGolQ+7Ku160LCO6B0lJ3PE8ejRmaTk1aQWr1tH0uWhmu4ns41DocXV7sFC8PqnS6XsNozajfThE+sIUVSSpNe1JqRX+E98c7gRcnCFeunXB3n1yRQdUPJMD/+0M6w6QDsOVUoC/GfD/mUnGW02aqPKgbccdOiYGJ13gX9O6i7qlrP2waxhkqMwjREJIlT10SAowGxS6VzGQSYwtfI5op988eJBPkCJ+HtqfFedpsQIrVTjjO7psNyYizDtLsx4n0bEKvMerOTiPBYy18CUhf1aKZxvxsN2Imui7JyleedeNRRrwA9ZM9KMfn/gWsUCAwNGph8QOcJun7W1xTlRPEaQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: wordpress
      namespace: dugulan-com
    type: Opaque
