---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ntfy
  namespace: ntfy
spec:
  encryptedData:
    server.yml: AgAiWmpzo7XYwKnO+47JWoTj+xvwHgB+n/OF0MiotRoFcuIX+rwvq1Z9Ku7/bjoSp4DC+U4SuSPn02dCL4BjO+mo3hM1stPjBf81t7FGJXbkPYWRQZcdzU5pBQ5yQbNPIRHNcgv5EMTeo3djLHfMNqzzE/UPRttzBonbl22p6s4fO7ZMIhlcWD0Gm9AH2R/VWAUBRLtQeX2SPaAzdhTs3rszZDiaYE9oBPIXtMp/XYNCdbZMvSIfvXy8MrLVJ8WjPXD1EUOlUWH2haqwaVc8P8qZ+5uFaUL1j4tGiRVz7hloTIOhWIbw+VLTWjAE6YR78b3UZJgdhGdXLg23Cth1AyqOKPvfHh+MWgbDFZsA4nbjt2IQCMl/CfCcxkYcJrWJTU7zkXBH+QBX7wG+IkAqwmXyvbZccjr/0zrvmDp8OTfmjEI8iUqQSvQNapXDvugmxwjKLu9+I+CnZNyeCNY+LI4qq8KMy1FpI11v/gxGZrAfHjOq2OinCBTrpxz5LlfKgtLQ9/66du7/82PewsBZP646vNlk7OxXyXO2WuiBOXhnR6FsoQeW1vXyFLdtHlbCt1kdGpsPncSVHl78VQQ0Rfc+mXubkubEHDiEt51KSkpVb9gp7Y6Bicya02ASD6dBy5dXgowFBFchVx9Ndvx28Bn0l3LYtCx9Md2dh8w2oM0YdWTYrlKueNOQfA10zkjkduRZNZnpDq1GjLbkkUFReR6S4rSxP+BVGJal5ezA/OBXG5ROL0bvLnVVwZzqDFCkY3AolJ14KU2Etuy4wLD9XT+SxsysHzRhVRajEkHN0VhvgGNANWF3F5gltesKvH+2aZc7/p4IWpz/u7E59+9gcZt+b9vVGLEsZeowgwFJAkN3lfgKcjK6xMAfZLokKhRHRuTRJacZdwTu7WpXHiz6qSGjhbAywEevIEOE/r9xWQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: ntfy
      namespace: ntfy
