kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres
  namespace: openproject
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
