apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres
  labels:
    app: postgres
  namespace: openproject
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: postgres