apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: audiobookshelf
  labels:
    app: audiobookshelf
  namespace: audiobookshelf
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: audiobookshelf