kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: audiobookshelf-metadata
  namespace: audiobookshelf
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
