kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: audiobookshelf-config
  namespace: audiobookshelf
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
