apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obsidian-livesync
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: obsidian-livesync
  project: default
  sources:
  - repoURL: https://apache.github.io/couchdb-helm
    chart: couchdb
    targetRevision: "4.6.3"
    helm:
      valueFiles:
      - $values/clusters/hive/apps/obsidian-livesync/helm/couchdb.values.yaml
  - repoURL: 'git@github.com:AndreiGavriliu/homelab.git'
    targetRevision: main
    ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true