apiVersion: v1
kind: Service
metadata:
  namespace: netbox
  name: postgres
  labels:
    k8s-app: postgres
spec:
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    k8s-app: postgres
  sessionAffinity: None
  type: ClusterIP
