---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgresql
  namespace: netbox
spec:
  encryptedData:
    password: AgBDaIlGCFKfOgSp5x9dt16N6QvfZHOWqybDjEnYTmt1rcE3tsju5iwRoX2D5CIeawQ5BL1I8C5OHczM4/rXFmPnyWxPmvbp8Tfd3jCsDKm2cpTKfl7SYVBE5OcT9EYU4/Y3P97SXu/z/0ix7v217n7RTH9MQvhJ8WMqlsvCj6B4x3f8CQ4xM+bhJWoazspO5u0APSmGvRBcGUTVm+99zf6Nk5I1847EbCjUnAXMT4tjQUJPPcT+3AMRjMLwunaONQpCLcf7ozg0J1w46b1S2jWBE9OXIKqPGeuXIH6O+Kowwa5eEsrJ0RcqVrraS9N2AGCHPDnchjLgeQ/YWqe4ELpeZbt27UHxDyp/SQVxkaj59BCDtG3+PrXEzDYOjd0hp262Dq+9Yk3K/Sr9gAvyNPUVFdvF8pal3mOKgU2BI1HkHigdrv5uBuw58znbuuW0rBrMfLsFe8Im2ZEx9LFUkXs8C9s7nEf4UAhE50NrQGXOvSmNNjCHPdoNMa8IUggKmC/4O6wdvNc/mnoXDMSlm1PkUbHix57L8wMc9XmwztjLxbnXvAWsK6VOUbiMJquoMgGv2JiC+QYWrTyvWXG3xVWWkrLzO4u7J9Nw0r9e59Bxi14LoPHGPKmfQzbXL1iN44vu4Km7fKIoBfGwU0wwGbX6oTHTfrt7wyNHdVuupcIJMaRHHll4hNygfuZkwnEU0x+hzvFVSjw=
    postgres-password: AgCIsA6f8asip2B2UOeLwp8RYqcrifTeahC8KiHcVwV1r4NqnfzzRPoxgHbGQtY/GI3ZXQzK8W8YNZBGC4Kc0q2YqRpxTFutVOSwVBhDtrMwHrcm3X9e9NIhCz4Aizmd3qoIt4kexaoGQMJtw4n8n94MDqVjSBMgJD4+Jnot3mJ6jOeFYCTk92BaxRhkI1eMbsD45EBqvdMv9LeLpXXN2u2CQg0Tuh6Jlf36cdO1+/m9jR2USEYCiWYYVWGsyBJBiEjU+kLgnGE3U+PDCAQ4cS66AZ2e5Rphk6VoHfmwlvGpjr91jTWH+UWkkPd6t9WKCcPFzIm2Qdb3x3WHEDJtVh3RM0USknKFVzxm08+EETAqbiP/Fy9wvEsPkpFRl2On6LmTlSbdD6uFTcgmVGJSsr/1id1oOU8nhFhIfk2IlznRg/uQV+B4z7YRfNzLq0GtY7W5chc1EUDfD08yxG87NAR2DDTqbP8UiiZQUUSc12z8L6cO3/pBP82EG4EbNAzO2OK4QM8p1fjDF2wSsx//Rvs5neU3lggrpDwRCxi5QNOxAOKWmA+3rC2ASbEfQspvBDgJGIJv9btB4isW8kbfGCz2IgQ+DRlsIeYWJBWIynn8mWYwegeMs59L5iOzbUnu2XU9hineuuj9nJblCHPdjSIVlFbx4MePeUrx8+IHjBlvZKTLd0/qDj8DukvzByYxZPw557CjTZc=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: postgresql
      namespace: netbox
    type: Opaque
