---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgres
  namespace: netbox
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCXdGjJPBs/UPhTM8izZtr9lkD/a4YepCbyRIUzCQJlX5d2hgWDeESEkTF8WxxGVjua2tv2Yiczy0ZHewsNoBdMRipLiaooQJ+Kqp6tOIlOudaAr8VcTp4PmDMSzTTymKw8CEC4ipohIXETEAzBNviK1mA26kG6QNDGTwUuNEoG4YRFYSdf8UzipW+99Q6aBpJ3KQXCw+7af8mIixWb1lWUFN3sHlAHE6C8PnrQnNLkYNmksegpfYnIUnGPTrVDJ+Swf9eyQ3E4ir75fG2uuXpnYOSoZYf6wVL8TJsl+b2rKuI+d4+KjhtATbcsqD8tCiHtSZ/Sa+86m79md2b+1XzIR3ejHcF3kk+G8nCethS7Bnr9HoZRyeQSnNv/Y5DSm20V3rII6VYzCn5fvezHDfV+YWzpASgDwlKwOMzV+QGeNw9aJnVpammKHdTiT2TukD0CwSfFNel5a+7bH82Nv1OfPWJoSY2eXnHjjlDfhWYRkPkwz+pg+9qFAlJ9+ZWO1264uQCKr3WTjgAT9G+sKyPEEonYwIgJJLR+/8RIhCGjFlVVUpOBdu4k8YRTbKfWVy++Zyef1dErbAoLWm19DYcWdGfrGSTGrxVAVj4fFy+oxqVfs0h5jUVueFnSx3tg7vHXIY8XbS/wSFG87kENfdlX95SO9/Nl0GYhkbvJSJiPSk44WiogC8SKdcWYo+x0aW44V1g/0Ps=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: postgres
      namespace: netbox
