apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: redis-cache
  name: redis-cache
  namespace: netbox
spec:
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    k8s-app: redis-cache
  sessionAffinity: None
  type: ClusterIP
