apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    k8s-app: redis
  name: redis
  namespace: netbox
spec:
  # storageClassName: nfs-client
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
