---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: redis-cache
  namespace: netbox
spec:
  encryptedData:
    REDIS_PASSWORD: AgCLKE4CEFaIa3sLgAWszrKMFWcjkZ2HOe/XDP2VW6W6Zhv8tiyUk8cxEjTNABBd5K786Gpdvnv4bLPcRK+Z+ANyCnyeEYW97uNHKCqwU6KAw+PIzF58k4Fd4NTW8kN3wtH+ytxP+/mErBlL/ovB4fipVfd+THxfl6r+mxbzIq5hEW6JulmSk+/QGdpN9AS4GUpfqfILsLt2XDqa0YGjSH0AX98mE9KqFhxtl/nazk0WUFHCF4oT+tMh4fwv24UuoempDwm6NUKK7YpE7mZEibfl0zuxjtoayZnTbZq4gpaOsjoMXKt94bS8foNBWdASqHVmNpctKeXOfsrpEdMy/IVhClYUZwWjm2gfsAC302j0vQrAKbu9F3DnLvKL2E9M26ux0JPsRr+m9GUDJ14FzNQ3upzKYwdlhBjol/vZ7QFibiSz9XSSuyeOJ+10uSwX+jmxuBgdIAm/xCzbjQwV+2/hVC7XcV0caLHqWVPGHI/9MfU2BDMDEsA1dsN6A07qOv/reiyrNJ09lVPQtKA/WOtqB/HfClxWjWOTaucveKBDQkzJw2DoTg7oTexFSU8m0igAN2+q0X6iocf245F8XjOlGSZWQ1nGXL7tro2uMOCPw7MDSvYThaqdn2Kxcwt5SGdrhXWV06eU2RSQDn2/9k8NkdMxP3nnTXJdrBxlymncIhGGPMfZHZB91lWNd3XrK+j0HtzTZXM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: redis-cache
      namespace: netbox
