apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: opensearch
  labels:
    app: opensearch
  namespace: graylog
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: opensearch