apiVersion: v1
kind: Service
metadata:
  labels:
    app: opensearch
  name: opensearch
  namespace: graylog
spec:
  ports:
    - name: tcp-9200
      port: 9200
      protocol: TCP
      targetPort: 9200
    - name: tcp-9600
      port: 9600
      protocol: TCP
      targetPort: 9600
  selector:
    app: opensearch
  sessionAffinity: None
  type: ClusterIP
