---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: paperless-ngx
  namespace: paperless-ngx
spec:
  encryptedData:
    PAPERLESS_ADMIN_PASSWORD: AgBKj25QdbtIYc+cWX9i0/6G6O0sOoFYvXMupbUAYqBxJYJ2v0Pf5hYucIUSjazxGQbcUULPzCx+34UIV6vBzuCyJ8pkmQB7Nyi388q68VKCjAplwvh/jjqyCGI61nXFzAY178r/Se9Bs7/y4fPSEHAew9uMNNAhHvFYqzFcr5dN/+fapi3KkZW4MhWPnnJTakHL1y6ItElXBdSdhlU0TnImR+2JNsMc8/2YksdnjVIluHwMbBanvcdQFyQZKWC6I1vlSqKjrszCcLa/elAamZ2sBLBKR7Vg0uPcjCHsvEsyuP+KHEkNmBj+yaMSClpjdSU7psfoYNjhEThj4uXJm/ZXXEY2OlxXTvov6LHVk1gfTD6CdHrMjT6mZ2vP4j0VIT63V6gWjvu/BXON5WwK6n9GRaLkrzIzYCUlIRKFh4tTP91Q8qV1+ZHweJ01V9HjcL8iB58xQrOdo/Md1trTmGaW2mTIsGgohdN3YkEPCcnSGlhHX8HXH0Hwv5Df8XV3Cc/zVFRoJhOJAoUkXNdhgcOiaDFzMtE49c+NnXmPp0e7tnash+AHOtVXZoFhdVTSTJ6vqfBcsK6zkFf0wuplugayAuy1kZ7/SbERpiee/5UKnmLLkG1DumI1yNuVumnwz3/shuYl7hluOXNuZs8UJ0OEECbzjn6aRyG8Ak/zGgInw4ulfLBqo3iL/FceWBLkxtNYdBkRxohQPRZ2RL6TTzKPhos=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: paperless-ngx
      namespace: paperless-ngx
