kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres
  namespace: paperless-ngx
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
