---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgres
  namespace: paperless-ngx
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCDOaQUEqWKUemaoIT2XsUygQvU7uo+AppJEzjA97JCkickUxPqF5iwFM7wTypCgDjOCDCDp/4u7c4WkI5GAVEiNKFvaAs0hzakkbaVb+AC9ZF0sIlOdhIAXmwTQLxxX2gujEsbZNdcTY7ePPX9wci57GXnOYjPmTaW2FCBu1Dw7ZcyORZeyuobctHx3TvYXYMdkssjCMPphXVC1EgB1848aGqbePU/bIaqNm2h9ypZp6qSdhHen9lzyx53OUBZ4/A5u2SLGkTzSWFuEtvhBowNxwJnc9/yUDCmGLGSNNQdhPvqOml/ZMcU2TsnDHQfAvgNYU/Jw1Y8xkRTMrlWbtErF+bgft6W274q6KV61o2JfYn+yMI3M333r425jNFvM/0kbQ/d59KhFcMDx/qAs0vNnTgkxV6ogL+wPuPSNqVHBM4jMT84AXdSYOMWpVAkRc9Ffk3oWs3YclXtlAH2RSkXLefWiqIe5/VDfe/KHLfIteVH1sGGFGA14PkcAl7UHMubN/nBpzdaDQtzbh0kUxxBpqPbcV/vQ3Ow3N/07BfayIdMBp39D0Uiwo6AeVHX97g8UDP0U7qIZTpP1ZTn3Ne2BAHd4dfPlenwSdU5IrPEnKx8ax+cEobNBM2UlLrn1lTblxMkc9g1DiFo4FsTnA4dtXord/eVEbqGHNkefvGZHqvKgLmM4V3QKCISg7hnExSv4HtAvnAZstA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: postgres
      namespace: paperless-ngx
