kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv
  namespace: awx
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
