kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: freshrss-data
  namespace: freshrss
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
