kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: authentik-media
  namespace: authentik
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
