---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: authentik
spec:
  encryptedData:
    AUTHENTIK_POSTGRESQL__PASSWORD: AgAexzWcDvE3x+b4OmqC7pZ3f/+dderpD3jDxtHaFaSGz3MGiH/jXEi+L3ILra9np748nW77fLwAhvZkNDX97PXWRHXHTu6IMqiniCLIJaZAlH0lVto8g9vU4GLk0ygBgWxajsiPQm4UIbeNS7ISXZOY21ky9ROqsQkQkJMZmIpACKRp2wn11qmdAcGNoDnqyTt8ZHbLxLKS6zrMIhbLcLJSVOr28Y9MbO8RFyGYmDGcI7mgMiDs/HnZWVtFco9TWCPFJZtYljxhJEcT8Y1gJ63CQN2Jt7H5Dpv7/NHwAaBLMmluCwYYvJkQ/gA4lnrMQ6MMDzoYwmbBbjDW44A88vC4yEPAcGjUTaBnad7nhpnwglSFbEdmLE9w1WcMizgjbzZyUE7GEF7N9SZl1DzSU/ICMCFCFaR7FJJxWHUEFbvZ40P23ZzMi1YnjfwG9t9FEVq+kN3IOiPypB9rUEGdHq3Hd+GTURmiwZxVJ0TLxzdwe1vzdyJpZPSINQ4iJNxiKPc+e7zPeTpo+moTfihW3zXz4CPHWjfFawGyLjSKgzRG3aHQqOL7nT4GZ150GIY1/qVQdwndBTOFeuZ4akFaTe7v5GPaEzMSnrAxk6zcrJzSj0237/HgusNdix9VwHyM8+fqcXAnIrNFs6u6WHxacFUYOl/dJImz/HJ1ccB0VaF0rNCreIgaNqIQpQ5g0XYd46rcZtzVnCXL1fM=
    AUTHENTIK_SECRET_KEY: AgA1VmRPUepTT/Ptwivg4PUEsntLiCyebOZGNfutXD2VSkmWT91Jg6O0DXEP1u+KoGiop9VymzPJ4z2Pa0xDKs+Q7S6hUmpml0w6SD9Vk6t0IIiBVm1r7GoUtOeMpbvD2A2vUvQQ5GRh/YKWKJFfnuGudzrgpX5yK/ud+z2pFMqbSNJdY9xjxZLkbdz4XMWRUlU6lTFQlKCWZAF4yYsMjnu+jFE2OCS6KpxDTp9yunbmyt4O17Pg57QWoh0NoWIMcA7UuEiKPPTOCYj1tZsT6qKW5V6eyZY57k7NuYNAh4EGcRhva9NymZb9UuWaJRrUpiZBRU67d6tQDiDO7f8n39v3jaxSX3LZIlba9IA595cs7emniveyeTMuEmWhYWJCXHJITD9exDFk28wmheZXuxMRkipBtNCT7rBcgBpMO5QyqLYXhtzPUF2E3M6YHQEwg8B5cxmALhPjmkONSwHwiyBYz96Va1BFMuDhUQasRAM1W8FGXf78QBBD51YG+zBMFf7bqtUpBVuhhTid63GDsQTv/ZB7UZ1wYF+86Nde+S1zQnMNKFH2+tMSwYKeCqjaQAGGq/jHS7iaY+ZPNxNqJZjjxsNE6ibzdUeOgENQU2vRjtmYY0x7vkpwlpFSLPKaev6+QXtWCRhrX5U0VCQBeOKsEp2e7hg0crgVwsKyRh4jLAMsluRKqX14YhMcZMaEj0ItwIkwhl9FlXcV7nI9+5HXUJjMYCTYIg4Ug3H8Pao2eFOVlyNXiQPC5Y+n1M1W2mlS1dPMZlDQeF1g03hJ391gV9Ff9ZqrOACM+5CW0shqzw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: authentik
    type: Opaque
