---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgres
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAzuolUSKy2EUr9bDEczMUgkZWTnRQA+j6FHhh6nkhws6EVSSLHMwPmeim97eslOm4EGJ1m5vmaoIeXDMiV9/NSiVQ9Alo4A1ZVKS4Iffb9LFrEGvEwFIXcH4BVW8d3GNvKekrOsCIIwzMvCLgwDtfu6nm5MdlmIsUVzHyElGgfm4KmSwsaMZvP59Cd29WDubOS4alY+4LI3acLBuGx2deVg2C3joCTP5xdHauxA7LeyMQOOvnFI1EPIvPKjpsWmE1hIgZMupO0PjqDaP1eRyW5X9EACPAIekvWs4iZirlfaOIUQoov/02nnGqRknL9sGis5WN+Q455ihEaQO8CUj5OSYscm6d755AWHtvC7+Rwxmbf2hrpb4R9PNzTrG5vlqPhDi0UFRQ1O576ntPKbEWTh5dGRBPoM6g0qb0f1UwuDGHbDcBPzPE063nVXq/rL5fM4EzCMyTmjLliRBAz5CHDizUMgTGCZHWksBoqlnXYj3WTWVQXoYYmqMH/VT4raqktkfPlpDckvoM8tKL0d/eo9FD0xWg4uh7J71aSc0tDfxjqeIU9IZx1ThNXxMkWC2RoQOTq5X9lsOGuGyHVSKJXoR42MWPXj/VoAjwNwaRbdlJyYLMPe5QNYXH6ZIFAQEI3urHYPE8bJX64YQ4uJ+bqnrPX3s5q8iMvc5sbW49R6NimLakpuLk4YUogyl1aOymw2gAcDjA/6Kw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: postgres
    type: Opaque
