kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vscode
  namespace: magicmirror
spec:
  # storageClassName: nfs-client
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
