---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: prometheus-pihole-exporter
  namespace: kube-prometheus-stack
spec:
  encryptedData:
    PIHOLE_PASSWORD: AgC90PV6XMRwjsiK1xOSA17vsd3o0LtezxVLTPJS2O0QJApV+QNY+o8GLTxG9qqUAxJms60CqEVBv1oscfljWo4J1In8JBXPdBPDC4/XH/5VdPXttb7NM0dpersNL8qeYeOJCgL9aa4KVD0/PTrNGKAZifoEt3QcRTNk4t58CJ1xAtNKBQ0vBCwdvDCG9wZZn99bwNjJ/dJ1edqBWGDsLuXv3zBaaBlk3pzhd/pSfUCaB/xmqojNvNPIpC4HcP3cgacBH6wIMeSt8f3Jb6Zla/ykoxusOjMIq3A0Gr4Pdh3YibsCrlAh9u90ws/iNT8jWpRSZHq/OWWaS9XFDixeGH9YWT+HTkpAUS01JXNjZYCWnkS7RhLorBNOwME0zPsxYnA34+YID3HGNlpxCKjZwaci1SOj5LBdyykpA5rf6sakZBKTHwDolr1bK46S9VqBsRo5JZzbcnNHlWGE0Mi3+6DXrnNHT+9Y1OUIYl6OrdWsOQ7RIsgxEGwmaPajC6SKaqCR2Cvy91/9MxHfpuNv2QhVFqbtRgenjjME9SCpedh7wj5kY1WVux+7YizAEgRWYyiHRR6UXavtq8WQ0yYIcpCZmSCTwlz3r1Ao71lJrQbyZfywIgZ/FhNkBvC9MI0aDAvAMUfD55dlQP2m6eK0Jl8cxZLICPZ6ddxu/d6Ja22wCP4RLygjeoqBFchmsk+x4MXo2Xy14CT0mLPMtWH3rfpEMF0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: prometheus-pihole-exporter
      namespace: kube-prometheus-stack
    type: Opaque
