apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser
  namespace: adinas-gavriliu-com
data:
  filebrowser.json: |
    {
        "port": 80,
        "baseURL": "",
        "address": "",
        "log": "stdout",
        "database": "/srv/.filebrowser/filebrowser.db",
        "root": "/srv"
    }
