apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: filebrowser
  labels:
    app: filebrowser
  namespace: adinas-gavriliu-com
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: filebrowser
