deployment:
  enabled: true
  kind: DaemonSet

nodeSelector:
  node-role.kubernetes.io/control-plane: "true"

globalArguments:
- "--global.checknewversion"
- "--global.sendanonymoususage=false"
- "--serversTransport.insecureSkipVerify=true"

tlsStore:
  default:
    defaultCertificate:
      secretName: wildcard-gavriliu-com-tls

# service:
#   type: ClusterIP
#   externalTrafficPolicy: Cluster
#   # clusterIP: 10.0.0.30
#   externalIPs:
#     - 10.0.0.30
#   # type: LoadBalancer
#   # loadbalancerIP: '10.0.0.30'
# #   annotations:
# #     metallb.universe.tf/loadBalancerIPs: '10.0.0.31'

service:
  type: LoadBalancer
  externalTrafficPolicy: Local
  # clusterIP: 10.0.0.30
  # externalIPs:
  #   - 10.0.0.49
  # type: LoadBalancer
  loadBalancerIP: '10.0.0.49'
  annotations:
    metallb.universe.tf/loadBalancerIPs: '10.0.0.49'

ports:
  web:
    port: 80
    hostPort: 80
    containerPort: 80
  websecure:
    port: 443
    hostPort: 443
    containerPort: 443

providers:
  kubernetesCRD:
    allowCrossNamespace: true
    allowExternalNameServices: true
    allowEmptyServices: true
    nativeLBByDefault: false
  kubernetesIngress:
    allowExternalNameServices: true
    allowEmptyServices: true
    publishedService:
      enabled: true
      pathOverride: ""
    nativeLBByDefault: false

resources:
  requests:
    cpu: 50m
    memory: 200Mi
  limits:
    memory: 200Mi

rbac:
  enabled: true

# additionalArguments:
# - "--providers.kubernetesingress.ingressendpoint.publishedservice=traefik/traefik"
# - "--providers.kubernetesingress.ingressendpoint.ip=127.0.0.1"
# - "--providers.kubernetesingress.ingressclass=traefik-internal"
# - "--log.level=DEBUG"