kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mealie
  namespace: mealie
spec:
  # storageClassName: nfs-client
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
