apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: browserless
  labels:
    k8s-app: browserless
  namespace: changedetection
spec:
  minAvailable: 0
  selector:
    matchLabels:
      k8s-app: browserless