apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: changedetection
  labels:
    k8s-app: changedetection
  namespace: changedetection
spec:
  minAvailable: 0
  selector:
    matchLabels:
      k8s-app: changedetection