kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: changedetection
  namespace: changedetection
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
