apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: selenium
  labels:
    k8s-app: selenium
  namespace: changedetection
spec:
  minAvailable: 0
  selector:
    matchLabels:
      k8s-app: selenium