apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adinas-gavriliu-com
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: adinas-gavriliu-com
  project: default
  source:
    path: clusters/hive/apps/adinas-gavriliu-com/k8s-manifests
    repoURL: 'git@github.com:AndreiGavriliu/homelab.git'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    # automated:
    #   prune: true
    #   selfHeal: true