apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  project: default
  sources:
  - repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: "0.14.9"
    helm:
      valueFiles:
      - $values/clusters/hive/apps/metallb-system/helm/values.yaml
  - repoURL: 'git@github.com:AndreiGavriliu/homelab.git'
    targetRevision: main
    ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    # automated:
    #   prune: true
    #   selfHeal: true