apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbox
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: netbox
  project: default
  sources:
  - repoURL: https://charts.netbox.oss.netboxlabs.com/
    chart: netbox
    targetRevision: "8.0.3"
    helm:
      valueFiles:
      - $values/clusters/hive/apps/netbox/helm/values.yaml
  - repoURL: 'git@github.com:AndreiGavriliu/homelab.git'
    targetRevision: main
    ref: values
  - repoURL: 'git@github.com:AndreiGavriliu/homelab.git'
    path: clusters/hive/apps/netbox/k8s-manifests
    targetRevision: HEAD
    directory:
      recurse: true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: netbox-config
      namespace: netbox
      jsonPointers:
        - /data/secret_key
    - group: ""
      kind: Secret
      name: netbox-superuser
      namespace: netbox
      jsonPointers:
        - /data/api_token
        - /data/password
    - group: ""
      kind: Secret
      name: netbox-valkey
      namespace: netbox
      jsonPointers:
        - /data/valkey-password
    - group: "apps"
      kind: Deployment
      name: netbox
      namespace: netbox
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1secret
    - group: "apps"
      kind: StatefulSet
      name: netbox-valkey-primary
      namespace: netbox
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1secret
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
