apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbox
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: netbox
  project: default
  sources:
  - repoURL: https://charts.netbox.oss.netboxlabs.com/
    chart: netbox
    targetRevision: "6.0.59"
    helm:
      valueFiles:
      - $values/clusters/hive/apps/netbox/helm/values.yaml
  - repoURL: 'git@github.com:AndreiGavriliu/homelab.git'
    targetRevision: main
    ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
