apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ntfy
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ntfy
  project: default
  source:
    path: clusters/hive/apps/ntfy/k8s-manifests
    repoURL: 'git@github.com:AndreiGavriliu/homelab.git'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    # automated:
    #   prune: true
    #   selfHeal: true
    