apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackbox-exporter
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-prometheus-stack
  project: default
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-blackbox-exporter
    targetRevision: "9.6.0"
    helm:
      valueFiles:
      - $values/clusters/hive/apps/prometheus-blackbox-exporter/helm/values.yaml
  - repoURL: 'git@github.com:AndreiGavriliu/homelab.git'
    targetRevision: main
    ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    # automated:
    #   prune: true
    #   selfHeal: true