apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  project: default
  sources:
  - repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: "2.17.3"
    helm:
      valueFiles:
      - $values/clusters/hive/apps/sealed-secrets/helm/values.yaml
  - repoURL: 'git@github.com:AndreiGavriliu/homelab.git'
    targetRevision: main
    ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    # automated:
    #   prune: true
    #   selfHeal: true