apiVersion: apps/v1
kind: Deployment
metadata:
  name: addon-mariadb
  labels:
    k8s-app: addon-mariadb
  namespace: homeassistant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      k8s-app: addon-mariadb
  template:
    metadata:
      labels:
        k8s-app: addon-mariadb
    spec:
      serviceAccountName: addon-mariadb
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - image: lscr.io/linuxserver/mariadb:11.8.2
          imagePullPolicy: Always
          name: mariadb
          resources:
            requests:
              cpu: 50m
              memory: 900Mi
            limits:
              memory: 900Mi
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Berlin"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: addon-mariadb
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "homeassistant"
            - name: MYSQL_USER
              value: "homeassistant"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: addon-mariadb
                  key: MYSQL_PASSWORD
          volumeMounts:
            - mountPath: /config
              name: mariadb
      volumes:
        - name: mariadb
          persistentVolumeClaim:
            claimName: addon-mariadb
