apiVersion: v1
kind: Service
metadata:
  name: addon-mariadb-externalip
  namespace: homeassistant
  labels:
    k8s-app: addon-mariadb
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/loadBalancerIPs: 10.0.0.40
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    name: mariadb
  selector:
    k8s-app: addon-mariadb
