apiVersion: apps/v1
kind: Deployment
metadata:
  name: addon-zigbee2mqtt
  labels:
    app: addon-zigbee2mqtt
  namespace: homeassistant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: addon-zigbee2mqtt
  template:
    metadata:
      labels:
        app: addon-zigbee2mqtt
    spec:
      serviceAccount: addon-zigbee2mqtt
      containers:
        - name: zigbee2mqtt
          image: koenkk/zigbee2mqtt:2.3.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: tcp-8080
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
            limits:
              # cpu: 200m
              memory: 200Mi
          env:
            - name: ZIGBEE2MQTT_CONFIG_FRONTEND_ENABLED
              value: "true"
            - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER
              value: "mqtt://10.0.0.41:1883"
            - name: ZIGBEE2MQTT_CONFIG_MQTT_USER
              value: homeassistant
            - name: ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: addon-zigbee2mqtt
                  key: ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD
            - name: ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_ENABLED
              value: "true"
            - name: ZIGBEE2MQTT_CONFIG_SERIAL_PORT
              value: "tcp://10.0.0.226:6638"
            - name: ZIGBEE2MQTT_CONFIG_SERIAL_BAUDRATE
              value: "115200"
            - name: ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER
              value: ember
            - name: ZIGBEE2MQTT_CONFIG_SERIAL_DISABLED_LED
              value: "false"
            - name: ZIGBEE2MQTT_CONFIG_ADVANCED_TRANSMIT_POWER
              value: "20"
          volumeMounts:
            - mountPath: /app/data
              name: addon-zigbee2mqtt
      volumes:
        - name: addon-zigbee2mqtt
          persistentVolumeClaim:
            claimName: addon-zigbee2mqtt