apiVersion: v1
kind: Service
metadata:
  labels:
    app: addon-influxdb
  name: addon-influxdb
  namespace: homeassistant
spec:
  ports:
    - name: influxdb
      port: 8086
      protocol: TCP
      targetPort: tcp-8086
  selector:
    app: addon-influxdb
