apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: addon-mariadb-allow-same-namespace
  namespace: homeassistant
spec:
  podSelector:
    matchLabels:
      k8s-app: addon-mariadb
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {} 