apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: addon-filebrowser-allow-from-traefik
  namespace: homeassistant
spec:
  podSelector:
    matchLabels:
      app: addon-filebrowser
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik