apiVersion: v1
kind: Service
metadata:
  labels:
    app: addon-vscode
  name: addon-vscode
  namespace: homeassistant
spec:
  ports:
    - name: vscode
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: addon-vscode
