apiVersion: apps/v1
kind: Deployment
metadata:
  name: addon-mariadb
  labels:
    k8s-app: addon-mariadb
  namespace: homeassistant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      k8s-app: addon-mariadb
  template:
    metadata:
      labels:
        k8s-app: addon-mariadb
    spec:
      serviceAccountName: addon-mariadb
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001  # Changed from 1000 to 1001
        fsGroup: 1001     # Added fsGroup for volume permissions
      containers:
        - image: bitnami/mariadb:11.8.2
          imagePullPolicy: Always
          name: mariadb
          resources:
            requests:
              cpu: 50m
              memory: 900Mi
            limits:
              memory: 900Mi
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: addon-mariadb
                  key: MARIADB_ROOT_PASSWORD
            - name: MARIADB_DATABASE
              value: "homeassistant"
            - name: MARIADB_USER
              value: "homeassistant"
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: addon-mariadb
                  key: MARIADB_PASSWORD
          volumeMounts:
            - mountPath: /bitnami/mariadb
              name: mariadb
      volumes:
        - name: mariadb
          persistentVolumeClaim:
            claimName: addon-mariadb
