---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: addon-zigbee2mqtt
  namespace: homeassistant
spec:
  encryptedData:
    ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: AgBc5HwWw9FaR34owQASEI9yqiORQ1MISTalNBdqW//bt6M4TGNy85jdha8t5liegyHgWtgYYiKvleGPOocfy9oy8htWpEdgAovn7cYea81rwt4kNULZU+pbqpfh2xjkfHBrhowN3R0CbVhR3BGXiu77yZpqY0DAYLEifTLNCUgdxiVn8w1vYDvhBm6urwXDEWBRcbtv2PmHDScYIn3MSLDpX/dfWYChmcOF+8NkmjB1Op7nYk6L87plPeDwM1vmPV+qSdLHOcFaQy/x+Dr4ajhjYW/9q9ezPzsOtMaFHyuOXtsVrEPD+K822wwb/OaO11J+FKeHUjZUK6e6buCQXaNC89oOa10fxp9BB2FviuwT4tnns1Otb0u4w9iqWqtig033gLcwjrv3IKgtAaBXvssEzC0h9xaK9J2egThsK1lcUzcbQk5vO+TLs/h05LukT4KPkBmdhtnO8DraMjbGK1GqkSslqCC+Xrpr+R2C25AOfzdU+RoPKdPrH6ubJk7Dl8jkN32PyC/dJMQSxN1FJINMY5TmdfgabMYxndnFRGOcMiJtau+F7rZEZH3KJoY1YOTi8amk7Xt2cR2xRVCNAqnsCbMu+MrKqZ6SqbbbIH/OVhukAYkgr3JL1nn5oNQd9H1lQ2h+YksKMhyyBl0PAT7Cf/8VpzRqK6dOmgSDiKQ+i/4vZ9iXUtPgziAY5Uexm2DQuJPcUuBh6NeRITg/
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: addon-zigbee2mqtt
      namespace: homeassistant
