apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: addon-mosquitto-allow-same-namespace
  namespace: homeassistant
spec:
  podSelector:
    matchLabels:
      app: addon-mosquitto
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {} 