apiVersion: apps/v1
kind: Deployment
metadata:
  name: addon-mosquitto
  labels:
    app: addon-mosquitto
  namespace: homeassistant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: addon-mosquitto
  template:
    metadata:
      labels:
        app: addon-mosquitto
    spec:
      serviceAccountName: addon-mosquitto
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0.22
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              # cpu: 100m
              memory: 50Mi
          env:
            - name: TZ
              value: "Europe/Berlin"
          ports:
            - containerPort: 1883
              name: tcp-1883
              protocol: TCP
            - containerPort: 9001
              name: tcp-9001
              protocol: TCP
            - containerPort: 8883
              name: tcp-8883
              protocol: TCP
          volumeMounts:
            # - name: localtime
            #   mountPath: /etc/localtime
            - name: addon-mosquitto
              mountPath: /mosquitto
      volumes:
        # - name: secrets-volume
        #   emptyDir: {}
        # - name: localtime
        #   hostPath:
        #     path: /etc/localtime
        #     type: ""
        - name: addon-mosquitto
          persistentVolumeClaim:
            claimName: addon-mosquitto
