kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: addon-vscode
  namespace: homeassistant
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
