apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: addon-mariadb
  labels:
    k8s-app: addon-mariadb
  namespace: homeassistant
spec:
  minAvailable: 0
  selector:
    matchLabels:
      k8s-app: addon-mariadb