apiVersion: v1
kind: ConfigMap
metadata:
  name: addon-filebrowser
  namespace: homeassistant
data:
  settings.json: |
    {
        "port": 80,
        "baseURL": "",
        "address": "",
        "log": "stdout",
        "database": "/srv/.filebrowser/filebrowser.db",
        "root": "/srv"
    }
