---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: addon-mariadb
  namespace: homeassistant
spec:
  encryptedData:
    MARIADB_PASSWORD: AgAAkQUFFh1NNeY6d7FtTgV/QjJs+SkSfE1BxFPuQtZiIWV9ffItHHffOWODJYhDt75KuID7tkUrFikaccG1tEJpzulZKVhYvtHwy0KNUX6KjXwDDet+BYLdzxXJ8pcjt97hkvHXDYhpVkM0Quvs6Qxgp3sOH2PgpQNpCTyeR0UxqtuYeIeTf8h243WJhRldxBvwHSj0i/juiLhM1Q3NVl+4LRqDtXYt/ys1woHdqtUmfl+VKCT4HNgplaUrOtI5fMn/d8nwN3pDhAYlYsa5wzVoegapkwAKf1fMEiNslqfRZQBgvAXZvrn1F/Ap6lAAN9U28sqhXqNDGxRAHsMdwfgX5iuwATzQuziUuDIJcA3hDTI3in+n71+PUnSzN+2l4CO07NRxOPzBJoWoiPnAEuluOQl1MONLnEiymiZwyt9+WP0ZeKu5UFGzeAZF2UZ+E3gkmQ2rZVnfzLH76YI0NkvUAXjJP3zSDsXL+rSkcJXjcl4axQxa9AnN8YERmOW3KtSitfsc80YnHju87QSk1tab6fmUrCUef4Opn2hz0jMlJkbh60FylMIPKT62zFahg4fuo7eTs2OT/sTOMWei1M7t3Q9PMqpFddgm6fD2FjGQ9l/xuk/PD0HraeBDqcgi+jD40SEJHSyPlYAlIzqd+Dp97OtW0xvvm8M01H5m/v2ZVBUvJKpXjlkxSLrRBYgY6+UGXmQdQVmq22MAvXyk
    MARIADB_ROOT_PASSWORD: AgAbq0yjqTQ/pZkytHt5m2dAezNo7a/AYRpfeWgoyDF20qB6SZwKkID6J4eeNu9259dXRYv+xgQCI7r3a+r745cbUr1Vw7X2zmYnYPIw8ZoA7dHNLJYIXWxBJTXdPuxmXBq1FCuQek7HxoBYpRjGoMTgUiHtTgNdgA8K1Id26K9oZpcWk/RYlVviRk8M9pTCNww1JFBJfW2vHb0RsBjGReoid+Y3zBhpqq7Nj8JSLi1Cu6H3EU1agW9Aa3W7M5jDf8PwNTxclzkYZZArbCTZzzW/OLUqWM28L1apnGP99AaiAVoDtP6guU4HVkVt3+9vILjyPJZskNh+K6SCH0G1Pp1ve8TjRTwa+sbzGko3j4mf52bqCLboVyCbim1AfOVcihHNeCaxn8iSmKMOoTlHU1gAVKvb1BPtxxlCsiTEi4UvRUwd/IxKgHOj4qkiYvxRvLvOHy1bTqX9T7i85LmvIz6SJTZc6JtCLCZnwVlr9DNZZDA/kL2evVBLojE+JwAt9KlbSuf+ZTyDSNN0VxuEH1M78YYM2FeBO0fG/p7SWZbP+CQZtFK1gyDySqjikHkCqeQYG8QpTZjzPJJ/uXHHzQms08HsThwxCHkVZgjmmKZcGwVKISIxPcNycPw2Bv/1BOo0IDU698MTzEZp3OR6inggMVCkajjpFNag4iYPFtJMBleJImmkbx7ar5qUPN3p3yiEg0jnWTM1XQF+0kNr
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: addon-mariadb
      namespace: homeassistant
