apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: addon-tasmoadmin-allow-same-namespace
  namespace: homeassistant
spec:
  podSelector:
    matchLabels:
      k8s-app: addon-tasmoadmin
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {} 