apiVersion: v1
kind: Service
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: homeassistant
spec:
  ports:
    - name: homeassistant
      port: 8123
      protocol: TCP
      targetPort: 8123
  selector:
    app: homeassistant
  sessionAffinity: None
  type: ClusterIP
