apiVersion: v1
kind: Service
metadata:
  name: homeassistant-externalip
  namespace: homeassistant
  labels:
    app: homeassistant
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/loadBalancerIPs: 10.0.0.42
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8123
    targetPort: 8123
  selector:
    app: homeassistant
