kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
