kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: linkwarden
  namespace: linkwarden
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
