apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: linkwarden
  labels:
    app: linkwarden
  namespace: linkwarden
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: linkwarden