apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
  namespace: linkwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v1.22.1
          command:
            - tini
            - -- 
            - /bin/sh
            - -c
            - /bin/meilisearch --experimental-dumpless-upgrade
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              memory: 1200Mi
          env:
            - name: MEILI_NO_ANALYTICS
              value: "true"
          volumeMounts:
            - mountPath: /meili_data
              name: meilisearch
          env:
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: meilisearch
                  key: MEILI_MASTER_KEY
      volumes:
        - name: meilisearch
          persistentVolumeClaim:
            claimName: meilisearch