---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgres
  namespace: linkwarden
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAQcyY807LEZ3IDtm5giukNThtijOcA6A9VgtRyAgSW0eMRnEsEnl4Hxd34C6vGAvcCYMLucf0Pwu7UTzn8FkYrlLvxpKJs68kpXSkmUOcIkpTNNCVX95iOYn2RYBXqlijmhm2gkVcy34dhxh0HsqFsHho5HdYsheZvXe1VFI/wElrZecR6nOJDiV74zaPdmir38ug5HXZonnhsgd2QuYPFwhyspav21AZhc9JZOJYiTTmKz+vuq1bMwYi0+gRe67RhPuo4OIHvAJxJi+V52Mcm3nXmiR7O6fFOlun641/NSaXMeIHixjfoyDiaXPUs7pTXOY03V1EBT12moEZEKLj/fwRNC6BfrjDUbfUwYovmwfJWTPHDUfqaVUidGBSuj+Xg8kFl/FyupEtQnJ1e1snJmNqyGPeyBsyKcU2+ui3Z+LZskksATveUJ97LiUKyyppzOQLblJlaMsrwPxioUG4fvCT1mt652LFb9CkcM05OkKuebAJhDi9I+gR+d529hDCvB1fcEMNQLh6XN0fR9nXTteZAVzqJ9tk0rcVy3E5ZR2e0s74gdvyrDi4IGzG8KkhJ8N9qpDAqn7NaZp2aOX4953mApJcwxHEhlnvsPy+ZMrAV0fPcywEGLgHYMmd4hBx+M7404TvAGaLCQLXC8SOsXOb6VidCM0Toh3wnxGBrOeH/ms9uWjVaGhz7d3qVIJBDdaxgZjPg3lMH
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: postgres
      namespace: linkwarden
    type: Opaque
