kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config
  namespace: magicmirror
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
