---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: grafana
  namespace: grafana
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgCEOxULiv2mUYCp7D4FWpu/0gx/cqLa8u+zpJXfosfMAIprGo5ScJGoE9jnRfEVTXxjaj4Aeds84lB2QKmNYfx86BKfjqbECDT+RLuFcrMSTM0Z3SA0JWYc8TtIhqEKDc/HSs/NRa7mN7huRwK8FXJCs6xj37/cPf5dj1Z3KmrVHnA0g4Sak+aGNh9oPogOQlonFv6HYQ0wJVBURPLvxrtkI/fBdjVhI8UdQWzxZgUd+XommXQnObAUGjSSaayGBH/uxkxe2u/NnzWcCwDmit0jK3IXUmSRQ01yzcn6Arh50I+GhIz+K2icvq4ibx20D2hGPYtOkMDYstVI2FI+2gQw8H3Q3TVkUL5f+J/RRdwqVJ2/hBXn3V7svRClATcBpo7tTY45SgWgmtdyaN5ki+mDTZjl+13xDvfMJxar0V6/BlZZmVk1b9asOninYGJX4b6ro9osZr8+pMGs+FxQUHhhe3LbZL0vzlpJKKLc2cxEVQPzVQnQo1aZa3jvhecfi22FzD1aX51NHf7/RhhCeyZPc+GhdrwvGlsCHaO2PSZ9UaTSUa5+fFCR9PEh185jy1SCo6t5PZuRy5DXWdWBJwJefjovmqSS8nCF1UO77e4V+krwnMF/zDH24/sISCuEDC7xKz05KQClpMMMdT9LH5GFSAP6vMYcl5Vxr0m439iWy2F5pStF0SZewmXHF3cdfmv9wjhZiA/0ypzi+M1uyg5wIXKzIP1+dKI7wqszAT64aQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: grafana
      namespace: grafana
