---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: grafana
  namespace: grafana
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgA7Iq4Gr1PKcR4DbJuhu4YPT6QXVTdWwbFKMpk3zzDdA6sVtAlnAqnO0rQwNFGpJoE9Pbv7brI1N4DQd4EbVPxAuecq00JjAsfGCRACoM6RucCfwX4uhBcqAUWwel4P44dUvtvD4m9vJhwsduBxTaQx2kRoSfqheoQJoM34TCsH9PGkv6XRkPDL3L0jzAgMjnCj9xzzxJCDPSJLXjQLZvVDXltm/x6fqv5iA1pQEJ7p+khBtCYKak9quKd9XjfqmVgxbhWGwHXq1Csm4rc8PAmhpTG0UM26ogebZbHYeLne/kh0sm+lpxkIZCQ6h/S6ozspRm3mp1YtUNGSUVmKM1/i23w6yBvJKHo21OqhWegnYC58qRV9n+P+LUyEIFs52lrJlrYSzgru4w/vm7W92PL0MYpMJ+zfSmLoMFcVPMSSu7xsS1OicHIoPiUhDTl+s8363AFbmr75jIOzKFbyttSdiNyVJz4tQUkXfLH0Rvc8CMnF3D+FINRVHK/YWM3XPqqtebHofLZ74HWMb/hF5GwnGKECvrVlC1gnfmCkncz8fl5R85wWK6kq9bFPVzeEN0LFnVoqZtBPZQnNLmpRHPpQ9whhtFszWOIyG7nkMt3qx72oMZC/TS9gKLwiMK/iOsc4e4itgyjxQkPa4mQ6U91txCt4T0awu4X48XP/d8Pz+ahhrPopxq/JWBiWy2TYJYe85HNrjL79PsnaO8q8Jwr2w0/hokWsgVtbu+DzbBiLGBB/D6MEwKKMq8dZABdx6GHLutnX7Yj+kAsl1zLV5F7OlbTkBJ36QICUs9w7acsfuCDKq3JyIq0ao4BZfg6SO9yfCr7Pmr+Lz831bnOBJ9T6aTiy9KwJga3lp3b6SrVY9A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: grafana
      namespace: grafana
    type: Opaque
