kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana
  namespace: grafana
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
