---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgres
  namespace: wger
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCRe6HeeDk5o76sfA8rwfnQwToJcDtpxo1Sx7Lu9dfCjasi3VPeFapidyxyaVJShCM4qKgHMPWh+9CZyUob1TulpK/vBAmSSVtAHENVnr+ylKaEfvmOk5Mrp02Qgxyae9tSgG5aQwLQjxZb3M9z5nxl7p/EeUOb2KS8SeIRMYFQRzeORMKEAA26fkSGLzgvPuj0sNHp0Qk9JHOKF/sgbJjMkETN4tFlRxTLDIUlrfoOWdrguFgDJti+3bSaHeOZAjkH7nlmw3ehrmMitZ28viLsDMtMD9WF5i6jrHKDqrTtK8bDHM57sdFsto5dhoKod/EoCiEBlN1dVuksjiLekzgxq+o3csPfGutRL8/LVcW+HdcNUEt3Rj0ofe1UB8FcAYlTNZs4IFJWdLH+gFkP8y5bmH8L5Zk/PX/7T/UyovMAB+LdoAO9QuUUWgAJ/KqenW2eYrXtr+igSZAhTn3Lkx0Ltl5Z2GzGYVk8Jh1ntA9FES8BB3FfhJfMk/NDho8BngQNCAkP38GAZApPgW78jJdqXOkLf5ZbBcSH0px/gNHDnTi+ivbSThIu85CzY9Iz5lSPkyLm8v1HFLSGTJPTL8wrQFhXqAjBE9a1YlKGygfa19laZo/YubwPBZzPrR1tWIGzLi7CyFY6N3GYT5tn04FWG624iI+ACMUuk1u8ytY76iHew9z06nB0driYgvb+UNiiu+HV
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: postgres
      namespace: wger
