apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wger
  labels:
    app: redis
  name: redis
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
