apiVersion: apps/v1
kind: Deployment
metadata:
  name: wger
  namespace: wger
  labels:
    app: wger
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: wger
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wger
    spec:
      containers:
        - image: wger/server:2.3-dev
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY
                  name: wger
            - name: SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  key: SIGNING_KEY
                  name: wger
            - name: FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  key: FROM_EMAIL
                  name: wger
            - name: TIME_ZONE
              value: Europe/Berlin
            - name: ALLOW_REGISTRATION
              value: "True"
            - name: ALLOW_GUEST_USERS
              value: "False"
            - name: ALLOW_UPLOAD_VIDEOS
              value: "True"
            - name: SYNC_EXERCISES_ON_STARTUP
              value: "True"
            - name: DOWNLOAD_EXERCISE_IMAGES_ON_STARTUP
              value: "True"
            - name: DJANGO_DB_ENGINE
              value: django.db.backends.postgresql
            - name: DJANGO_DB_DATABASE
              value: wger
            - name: DJANGO_DB_USER
              value: wger
            - name: DJANGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: wger
            - name: DJANGO_DB_HOST
              value: postgres
            - name: DJANGO_DB_PORT
              value: "5432"
            - name: DJANGO_PERFORM_MIGRATIONS
              value: "True"
            - name: DJANGO_CACHE_BACKEND
              value: django_redis.cache.RedisCache
            - name: DJANGO_CACHE_LOCATION
              value: redis://redis:6379/1
            - name: DJANGO_CACHE_TIMEOUT
              value: "1296000"
            - name: DJANGO_CACHE_CLIENT_CLASS
              value: django_redis.client.DefaultClient
            - name: AXES_ENABLED
              value: "False"
            - name: DJANGO_DEBUG
              value: "True"
            - name: WGER_USE_GUNICORN
              value: "False"
            - name: EXERCISE_CACHE_TTL
              value: "3600"
            - name: SITE_URL
              value: https://sport.gavriliu.com
            - name: CSRF_TRUSTED_ORIGINS
              value: "https://sport.gavriliu.com"
            - name: ACCESS_TOKEN_LIFETIME
              value: "10"
            - name: REFRESH_TOKEN_LIFETIME
              value: "24"
            - name: DJANGO_MEDIA_ROOT
              value: "/media"
            - name: DJANGO_STATIC_ROOT
              value: "/static"
            - name: DJANGO_LANGUAGE_CODE
              value: "en"
          name: wger
          volumeMounts:
            - mountPath: /static
              name: wger-static
            - mountPath: /media
              name: wger-media
      restartPolicy: Always
      volumes:
        - name: wger-static
          persistentVolumeClaim:
            claimName: wger-static
        - name: wger-media
          persistentVolumeClaim:
            claimName: wger-media
