apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wger-static
  namespace: wger
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
