kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: filebrowser
  namespace: adinas-gavriliu-com
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
