kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ddclient
  namespace: ddclient
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi