config:
 devices:
 - /dev/sda
 - /dev/sdb

common:
  config:
    bind_to: "0.0.0.0:9633"
    url_path: "/metrics"
    smartctl_location: /usr/sbin/smartctl
    collect_not_more_than_period: 120s

hostNetwork: true

serviceMonitor:
  enabled: true
  extraLabels: {}
  interval: 60s
  scrapeTimeout: 30s
  relabelings: []
  metricRelabelings: []

prometheusRules:
  enabled: true
  extraLabels: {}
  rules:
    smartCTLDeviceMediaErrors:
      enabled: true
      alert: SmartCTLDeviceMediaErrors
      expr: smartctl_device_media_errors != 0
      for: 1m
      annotations:
        summary: Device has media errors
        description: Device {{ $labels.device }} on instance {{ $labels.instance }} has media errors
      labels:
        severity: critical
    smartCTLDeviceCriticalWarning:
      enabled: true
      alert: SmartCTLDeviceCriticalWarning
      expr: smartctl_device_critical_warning != 0
      for: 1m
      annotations:
        summary: Device has critical controller warnings
        description: Device {{ $labels.device }} on instance {{ $labels.instance }} has critical controller warnings
      labels:
        severity: critical
    smartCTLDeviceAvailableSpareUnderThreshold:
      enabled: true
      alert: SmartCTLDeviceAvailableSpareUnderThreshold
      expr: smartctl_device_available_spare_threshold > smartctl_device_available_spare
      for: 1m
      annotations:
        summary: Device is under available spare threshold
        description: Device {{ $labels.device }} on instance {{ $labels.instance }} is under available spare threshold
      labels:
        severity: warning
    smartCTLDeviceStatus:
      enabled: true
      alert: SmartCTLDeviceStatus
      expr: smartctl_device_status != 1
      for: 1m
      annotations:
        summary: Device has bad status
        description: Device {{ $labels.device }} on instance {{ $labels.instance }} has bad status
      labels:
        severity: critical
    smartCTLDInterfaceSlow:
      enabled: true
      alert: SmartCTLDInterfaceSlow
      expr: smartctl_device_interface_speed{speed_type="current"} != on(device, instance, namespace, pod) smartctl_device_interface_speed{speed_type="max"}
      for: 1m
      annotations:
        summary: Device interface is slower then it should be
        description: Device {{ $labels.device }} on instance {{ $labels.instance }} interface is slower then it should be
      labels:
        severity: warning
    smartCTLDDeviceTemperature:
      enabled: true
      alert: SmartCTLDDeviceTemperature
      expr: smartctl_device_temperature{temperature_type="current"} > 60
      for: 1m
      annotations:
        summary: Device has temperature higher than 60°C
        description: Device {{ $labels.device }} on instance {{ $labels.instance }} has temperature higher than 60°C
      labels:
        severity: warning