---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: meilisearch
  namespace: karakeep
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgDEW6MXtIOw4bY/tBKzl0MFPYiog85fkgzf6K+1qswqlw6Y3qk78gochzyYX8OF0jTxJh+QSEnCpb1FTkCYHH40lvexh2no3gSR4iC8C3ec5yVdPHKJ1MxiUScQNV4ItoFaddGpBMaqURXsqGeC3MhkZOQLPF3WvNa+iv9fqQRI+hhngEGnpPil2lQqQj/BkFMwEwhcEY69w8edzRIOYmvRd0hogtTtt75uBv+dUnq3dzmM4nLxpJ+QIRDt8nEyFrJbZLJaBxiUK2FcVZVNPpZuf1P4tXVQNjxe5ZoBAlBfWxzb92IIZt1LkcoQhH4KbEYe7K1A/HkFxfMUmgQcOtVJa64XG86rLEEWQ/WY7Q/j8SOuRC/NHzZuVV/ooAZ/MbBl5EKC3ypjl2zfS4bpcPhlG15eVCLK5tAejQ3tJNCFt9KUfafuEzT2FtHBjNZYWhOaywLN1cgNFTn/z8HFVLA8pLjN79mDxJMYS6R6B3TEvPNRiHHqMMax7lMC015RSFAg477eEZIqYQ1ZoOLUzoAOKCxzEfBtFdsTmTRiLFs1NMi56GrEpY6Te02/PYlunDUP6Z+/svMWmQYgG/md5cwCu7KW0mSyyK1EVS0YAYu2+0XvPwbucyZBshAusJxZiSuiqnz+Z0dLKqll5Zjbss41tusolN0ftizp7bbhnLnwB0+tbt+cTiF7K5cnbMdBAg7q2LEAtVFRGv9YoGU1nCntxuvMcCWE2D219tJDkZSuuLL+ieGG+dxA54OXMQ/yZ7Q=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: meilisearch
      namespace: karakeep
