kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres
  namespace: umami
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
