---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgres
  namespace: umami
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBTMtrmjeGYUPIFXx9weQKx/XrDmZfr6YUND0dgmZQK2MBn9Pqqep7OIymj0N5bF4M1YIhc4fIkKoGaDE3lfNJY9NBnXvd7GLINM1k2smMc1t8y3BK2gd/eRbLhJeKjTZs3o2Gu4bOxVq3+VKdQeUGg+LPjubBER/gqWSNq1GExjJii4oBhEVcWZFCQpY2BUnHDDT8Isn5QhfVll3niu3KJyNTA5y6GVTxD4BnI43idJjBPXb/CwfrLACr+5N6mSWSwLns85Ez1kcNX3i4FSkgsxjz/9YV/VaiWbX31uESvqhRRkJN600MW1Bi/kcEx5UnUlPg5tTiOE099roxgqgtx4p9yrNSe+xE1GvzPxODOnP9W4ZkJciOZBuOcJcj7dtKGlWSzR72ON9ED/MieuiKj8mygtWMpFb1aQoJKCg1BS77BuHIV+ax8EKh2Ahi4mutziBdMMpoi1HKEB9K71+Yp7u//JbY7/mXlZ8dvcJKr4qg+3F0G9RUSmNcfnKF09212OeiCLGY9iemNOjPZBz7saWrPbM+3YeVyucu/6WuU4MOud6Odir3UOM0ntMMMp4vQ3rWLFQ2RYQC0Y9+vvedl39yTLr9zDkOe9PlAiaJPteFq6HO9anIXYbjDOpHHwkiaqJM0YSN5EWh0W/AjKX7hIT+qlqp5/CtsWj/QpF4+PLQMVzQUEZsTzjJyr/macnUAdb7Zsg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: postgres
      namespace: umami
