---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: umami
  namespace: umami
spec:
  encryptedData:
    APP_SECRET: AgAcPhUJnaR3zkkoolPPxTTVBjPaz79cjzW01U6ngkRIODPYFN4Reo6BehI/JYhzFBefkQynToXyfNbSJkHfwG/bGK4XU8vdXIryzBv4e+LxU9FxgSyeZw65TTV8IHN9ZzQM1tOrr5CDypHj0qZkq55IjbxztwTU4JuLx8GXYTyWIQhX+d3qv04sqDsaFnPxGRxS+m4h7iVJdEISdBpp5Vl4SNxTQEAzd6D7KzkzV4BHBMVwk11lVNGvuzaBHZ15w8a/X9MjXdBiKqk1jrbOljKzRI2JfKWPXhiJQVTG+MXjc+3lv/SXlekqe6hhtKcqKkupR0uwwkRIxPsrr46fyZU/F8pycxfzMrHBvnt58DwzzHUVyBIlXj8oy8SiHVNxrcJQagMretgq70Ev0na/W09TBvWT3o4joLDm4/MxA80BM3u7Wr98LziG7pZgDdoOXX6wKzkKfUsYxobcYoJK2yoEChMdZRqVEv/7IkKrodPT3VswMe1wflus5MQBVJf34i4TjzGFBgKmcWxEYIf239FILku9ek5ILTdaSR0jSSUry0aItp2u3RvN9fKxPnDtqZVnsoZKbMLQ9tU0Pw2fI44dJfVfomYOYCoNh+5CDDB34CnXCFEIAtOP91vL7PvQdPMLwEiuP7cNVpq82IZ5+kyuAhkWz2aM3x1O36Rt/0hIu7lB6Q/2BDDBPGX6KqiSa0XXpP+ZbTff4WocGo7c8cpB02c=
    DATABASE_URL: AgALYNW6aU4hFg3Ef7SfRGSLoji6Hw9RSIf4KLs0CtYAYAYN6WUhbONa9Vb3I5MkbA5QKMbsKXem5RLBDg234q2gFDvu/mDg36l0m/Sq0chn9CsmdlXp2Q71Qlx/faRc0kGb0g8/Gz7Nvk9xq2yj4miplVySpvh4nKMR6MIQP3aQJjOFHKEOH/7KkU8Q9+qv+b5SFWkUIkZ7Ohb5HjSwIHCpFVVrWJn4MEpCwT31P9SnK9TNY76R/aTYOckHvttfGU04xSoTCN5VXkCT8XMtOHPabRzd7OhF4oYmaJoAlP2ECuR+dPopwYIJEj6JhMv4P2Gj94K/0keQRZZrRxzZIk57nHC4BX0CLPs9BX2E0ieyeIW19rZRVJ6p3/yS5dKYtJsJLWpIokTlPpt7lzWblzYDmgw0hJckBv/aHVJRWhDGqUBUSJcmZ87g/VsIvznGk+PFrQjptJ4EKnnb6laxdhq5d6S9y8IwnTL+v9pTN07aQnSF0YUtQTKqzbp/orIhLWXj8Nt01NoNlNOHdhBon9CSZuW+r8OjEi3OoO29dEqCvzGmKaMSdTDQdfckS0txxTYNl7mihgFIpy1e37z9h/l2vgLHmLgXfjNC6cS2yp0djVYJYZCBsk3AMD7ZhtsrSe9NwR4t+ohVY/8CqCc0cxi3Wczip688PcbDlWsK81Dl8cfcLtko6OIvh2s30bufWuahP7DOSTHQgmOLgTkficiIF3aT+iynS14E39ai+rOvzkWV5iQWjfm946O0Yw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: umami
      namespace: umami
