---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: opensearch
  namespace: graylog
spec:
  encryptedData:
    GRAYLOG_ELASTICSEARCH_HOSTS: AgAJ8czMq/THo/k1MG4sAvPJ6njpyAHL3tNxBr5rDyChVIf1UVHiMONxngx2pwiy9N8nDFFbZsCHUa/+Z38urr0msB83pybSRU3rIfAatbfaf3ItFuC7tCeRIV2rt7xWXTE9haQrN1vCd5kd0vR2Yr+5QCSlNynR44T3M3H1dR/Zyhn4KJaeApu1sICm9DWpspcKrsMqLkp+/OcYHG5SaeICpNdf18HIxKLS2ImIb1jx1FNVpW4zyrL6HA9hJC6cts18T4TsraNO2jjRjU0IbrJedt6UsapBrGr0mqM0z/JgQncDZDZOKMgU3ynLcQLeNwSlZtR6rtDe8derEjJ0vbG6jYHCm/H5T6gs33DuD+m5sLljk6+vzQYzcBw0/vbWJ72EvgaofPH5bRBAdowF5jM2D5Zb0jgfL/BtlfEVR8Quyv6eya+nGzk+QJKlmiu7lP12/zIekYhHGTUbyC8VY5MfJUQ9LIRmTeVN1LcehjGHxkNhifWM5myyIcR6y2Xt4YdrwP3CD3koF8p9vQJxOhTCZ/xAuDbf5JPMfikIEQ++XSz6K0THOnF8GhmJP3BfqjvJsADddczH2ySL3r1dZuNBk7pc66kcTdbfjSvLDo7mM6GULemmD1U61x+6p9FpCUa7VSqwGVCNsqe3M1sgVeMy4s/VttL4KDMeFJZveIjNlk7wmNIXLF5FqrX8ZAvikvgN1Dr7StL2Rs5qCWVQa4DuNe/tNpIuhkVvemI5HQtSJtkehYxVPHMEmTaOBTAfn1w=
    GRAYLOG_MONGODB_URI: AgCNk/soU4zp6+k25yvogp9AswxsA4rgkPBDZXFwUdqGIdp9Umy7sMEyf7jn4bSqq08geQGPoYkZIE8RsexJdu6Q5j8K7sV+ZMoRZ20q1S6NlpAJfGtd8TH1fCDMAMjHeXUAjUEq3tkikGC1AKtPlZ+5g+rQ4IqsZ9FAHba6QmX6qSyXBjXkWMsgzDN/2Yq1BPZNMFVC2qqMz1/SCEMGdP8sRcGmkpTS7n1YgcMyKl9lSCaeZbhkJrN0JORe8lFJ9DpP5Ls6htGClyTdL+pwH0BGw6XorKfZs/JlEfSWQTufvsbfU/F8qB16aTbh2fyyIgWRLQPZa/ByTt+I+q8lPj6Qso1AX01inFmdLhXVb86v2EKDjBG1UWQsplhPRgfeB7KFFilyqAa1yvB/gH6Utz1VApW2EYxfD2ge2RK7LwwKtuGcaOAXoCy6117yqImXArGsFv9n3Y0/NCstQ6SMiyrCXfWB+T0t+PYHGOjFbh4+uLe8Eggo9VcWGb4KCCtM5Z5l5XzeUgPkwGPmtnMAN4UFdnWuCMpmOirD5R/ifsKznSSonvENe0fvHSkgkyoy+zYsEhYZJgweuKh55/dNkiEM5pNqDbQJS2EjaRdsvvaM4eyJW9PhQy7BwvpCy3qtXh/YwbjzWKuMG0DXHP69QmH99opExSusm/Bbx9Id3H1HyyujHazEepTc9CnVH2pf7hGGUSv6Hz+aUei1PQD+1GaxjicSUcnngxkw
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: opensearch
      namespace: graylog
