kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: graylog-node-id
  namespace: graylog
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
