kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: opensearch
  namespace: graylog
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
