---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: opensearch
  namespace: graylog
spec:
  encryptedData:
    OPENSEARCH_INITIAL_ADMIN_PASSWORD: AgALvF0y/4qhz4zMAcXO7IvI47K2uJhsKL7xWHv1IuguZ6BL10BAvSEtF9N/HdoO92lzRboVrHEeDd9SGXqeNy5QOq07iBoSPMu0A0L/WF2m18ag0KqoRXBsF27IUwWptl0cETXI89nInO1fnu30ezOoT2hub16CZon6ylZJW/83mXmYFdVhlmzEF/3qVoYDaRIFNzDvj2V3ZIfXCTI7vIgX4Yda56qmOEZFwHuuoCtyyraPZiyRfZpdEnngpLHdIDvIFlsX/Sa3Yb79NbZCo8ojWq18J3Y/6UkO66BfH+A1c2aXtHvZKLu1YMWz4ecNDSJlFiyboviJ+osOv80ekZJ/F9kIk8w7r9w0986JArr0CvO63TJZ7pjysBCECZG3j48ObzFpeiFL8tamyb00A/TWR94njNDxKlvfxTC/yw6pfupV4z2Wnkt7SNotR4IGMWzG5OpRJHscwq00shTXpoWYIiRuJci5Ri1/eyXRrS9LDCVF82KOxmZG488Gu8XzPUUytGjnXUH8H8oxP2zXjjgCvzkgs7N9w1fx1ryWVhBYWPHtt6I8UCqm9eHZmPOy9X7iqk2gtgA15IqlLQc4kFGlnzWjJdUoKETLGamgVau5amgQuvjnEp04lSvytL8BiWhayEpUlwDoZc7cjfen+a69PVTgpYWUCW0V9R9QYBbT6ggjPAKSXASxK3eEa0u5BqlRJdXaBfFBzwhtGO3ZQ73eamou
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: opensearch
      namespace: graylog
