---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare
  namespace: traefik
spec:
  encryptedData:
    api-token: AgCaD4oXzpnCEydKvpf2jlC2ugUOQVLD2vqn1tGo1c9H69VHP4GlQ/rNFntGD3sjAP3IEVzxC5V4MQx5Eifk6lkIQk89HkqqHGbglTdoG9M7NPeuLqZcoOrAmAiZUMYeD1YdH+m6Dg+lQ8fSGRRr828U/0bowSypCXH5A7WfwqyaY9vtJ3dJwvEnszpRmUiE2n5FmvQsCs65Ib3IJ4yv/KEs6V4svLXHYUbrAVXJd0YuBsRlneAgQU6sS80tysNSqpfv9w30iw5/6g5uFHrfbEIMcZPs1K3NK//RsZqzZBbW948xwzHg0klCCUaKOoRK83U0il4Snu+2/nUP8R8EAI8IOXPGnS/OBNw+9WV0Gx7O2YN9KwW+pl7NDq+dIHAdgxgsmCsx03A/3cMoBDqn7PhMZqHxDn6wnxQ8vnmPH79fEi5Lk8HDQKOotQiS1M52MMb154WnXwD2/3m0Li6uFIScP3QksnHBepss8aX0amDCDXT7NiucojRAH3/CZRHpy1NDEImJNAB32XNiyOUv5GLtinvhCSGLrXqNg2CzUG09sjjwRssmoI4AegPoNoJ9TJZTSe6X+cKLBKnAjpU/BWRlFvl6cE9HBtKG/eu4Arm94H/tKgjtjJQuM/TZb8D8zGOoL5UU0UHB38vzCiNSmcWfFqjo628i3Seq/f/jMPKhb2+O3KTOk189prbBw0GWtVzk2/zWz8A+sdLeuSRkeBG+MhirKUnuCHY2WZQTsCMDc/aLjZ3bM08X
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare
      namespace: traefik
