kind: CronJob
deschedulingInterval: 30m
successfulJobsHistoryLimit: 1
failedJobsHistoryLimit: 1

cmdOptions:
  v: 3

deschedulerPolicy:
  profiles:
  - name: default
    pluginConfig:
    - name: DefaultEvictor
      args:
        evictLocalStoragePods: true
        ignorePvcPods: false

    - name: RemovePodsViolatingNodeAffinity
      args:
        nodeAffinityType:
          - requiredDuringSchedulingIgnoredDuringExecution

    - name: LowNodeUtilization
      args:
        thresholds:
          cpu: 35
          memory: 35
          pods: 35
        targetThresholds:
          cpu: 60
          memory: 60
          pods: 60

    - name: RemovePodsViolatingInterPodAntiAffinity
    - name: RemovePodsViolatingNodeTaints

    plugins:
      deschedule:
        enabled:
          - RemovePodsViolatingNodeTaints
          - RemovePodsViolatingNodeAffinity
          - RemovePodsViolatingInterPodAntiAffinity
      balance:
        enabled:
          - LowNodeUtilization
        
service:
  enabled: true
serviceMonitor:
  enabled: true
