---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ghcr-login-secret
  namespace: hugo-gavriliu-com
spec:
  encryptedData:
    .dockerconfigjson: AgBndLqX55oX+f9MKYii//PYTg/E/nxp2jMmgUFqffvICsc5OgH+uSk/l+1dCsEpP4DO5gWvmjmlKwvViIn4dPjnwYUibNX8tCrzgSNnKzYekcm+PAO76nh2/bnbr05ZQ2kIWGjlSzKFg8PyCGepc0Nw3WRs4rtItRQdmftdI3yApfH4jQ37lh1iHlSmBi/oK4Kq+rULHXTVQ1OudNTMdKQ5MkOUrCFumK1PlERj44o9vF7L5Iog7utAMmz0e4XFHYWlgPBlVRdc8ayGekJJ+1Mo+4sN/Zo8ssU2AWWrTwoSho5UA4VAj9v8141r89ZVl28BGQprUih3XKTyWAr+JY8CdK1dImiXCBpA76NWewLScN4yLuBpHk3griY9rrgo46Hg8WLxMnTZOD2g0Xr8xvphYEiG2mtFlDobCrVTWel5OuoJNNzotlefb7B4LBAoSSoR3ra+kUIsfHAcfxaywvy3MI+UumdGWFDoL/wjMm1TlfyV3/aC+nuUFd8U9vhugC8VHxJitTva/axnR109tZPZd45fWqlOZsuRc1uOCB4doRFcYPOrWskLZaZU3ANEffxwOMKupIk7RGeQ+0Ostst+dNY0CuE3TysSrL9UB9tG1O4aKmBct/F5PyQvt/2zCDsmccDfwqgqFDxsys5ESk/0qYl78a1lQjmqylWMu39ENK96K4lCLLu5tMp5DhcJQ6VMGoo1hLA952TyR4/vbbeEojaiU2cr+mDYhLAs4g+sVnKop/bwXbuVXWDUAuoZq0T7r7N5PqHWPCqpemnOCSlApv7N6FJIe92NJdQPV1ENI5rhEF70S3WpBT/R9HexDELb249zKlSmQ7Fr3g8zYTbGUIeq5O8Nwa5iTmGy8/gw1OFd558/qEaTM4KZqI0KXpox8c5zP87PPPDJxePyqGGQYxlzM1qJF7xmJoWUHUMPE7OG+XSiYd3qQ4AWlq2+AQ9hL3HVZ/NO
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: ghcr-login-secret
      namespace: hugo-gavriliu-com
