apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: hugo-gavriliu-com
  name: hugo-gavriliu-com
  namespace: hugo-gavriliu-com
spec:
  sessionAffinity: ClientIP
  ports:
    - name: hugo-gavriliu-com
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    k8s-app: hugo-gavriliu-com
  sessionAffinity: None
  type: ClusterIP
