---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: firefly-iii
  namespace: firefly-iii
spec:
  encryptedData:
    APP_KEY: AgA71Kcv94wwWEuDhtlyATzrFHAoZ/MxXIe/9YUiGnBb4DwbwJMjod8hGLuH2walv5M1ZTu06U/99xs2JvLR5fpMQD3OEtjmKr0WK3osE46lFgmEY1U3FHQ0lxsYt1kSaEUPyZL5YLElpezdGBBah2zXofUJncBhiUpbd2Yd0yi2BFHGW15n5zeNa4Ih5htedph8aEIngeaVWTUrmtyf4vXJ9oQeT4S1UqN3uGq+Wv+ObJisqGbVL/s296+6FT3ya23TZYsNlhMZSwaSA2XMBaYHPzbIAVBGfsZfPEoZ9bRUpPsfEqcar9s4HU/LWo5Gv5QV82YSFq+XNxCAYvLiVUjXgx/Zm7yJJ5aBC6r1NijfCY0RM2Cg/D7c6lVIm3w54JTaDHn6lfAJXrOIov7Sb/jT4SnbmVqNuY+2e1rLmA2XBuuRCWY9j2Uf+v7Hy0H2BUryUJUMDYai174db5bzu0KFgmQsyv8xpBPGov/PP6DHT2vwPxKezArsTn/J4SYadTv00Iua/ridfW/iL1oqHMtpghqPo1EmumQwNk4kC3roZ4xBGCHstyDBQDQRUhKYSMAUkar8ScG9bQ8UlcPxEoJfAmwI7HCYN6dBdbr1GV42u15HP9h5kS3k/dTD9Kh3LX21YuMbBumq2TNj1gESA/z2EmKxzGK3HIFvWmcrC+ckoAXkHYpG4Sb5YzgdJnGiI8fro6knttP8UBkWrnCgbHU/2iD06vwRSQfc+Xo/loVpTw==
    DB_PASSWORD: AgAx1uSi+fO1X5z2/qg7vH4s4iu33Y0dpXHdYg6VCQNl/wu5YM8eru6kXf/tKRuEdD4X53gGbr+Vm+YGqByhCFzvQWGUkHHm+SPKXWkw355aem2ApuMAoMqn2tFmzG08Si5Ufs4Ci5TKXP5ogmPkXlu07rnRR1McKmtJOldo4hjPrY1j09m08cNCPc+46bVlQI5U0SLmrzL3Gw7kQs1bbP5nOwfUHm/ZI8sGjzJXhsdyhFL43qvvIMCQR2EX12F8XBTWVJaJxm7NrdEU1tMa/WVCfDc62Yv0MK2csb9yVtGCiYjzQWk6V/XE27e1FQ7cXx+1XzrKUfKb0nWSPWk15B4fcNii0OtzDaR22yRkAvUplHLBQW2oADskSaPthomJ+6s8hjqMsilqJv32pj64EHO71rTlrbDCiV6MpU3Eyc0KlzEVu6DCmwLV/PnBKn2C7HICZfpIWyOh/BCj+cjMVcI4QDttrT6Yk9xrultxPyjTb6G9HGgoPvCWhIeXtJrJ3XDlIWQQWlWOEj36ZF35SvGXLnItaqgpS0VwaqIYURhOUrn7yjrbV2qhOtx5eMVkuBeVejy+HRbcBJUVI0S0mVoGa72HePukwv6v6OZhOSJ/9wHLlwEfeYlJRV7v04CGI8VedfdjyMlUn1DlZralG3ZPCUCDWy1QbFS6qKXduCfNhIDJA0t0xr7kBgVpiAHn74203bH0he4e/Skx
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: firefly-iii
      namespace: firefly-iii
