kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb
  namespace: firefly-iii
spec:
  # storageClassName: nfs-client
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
