---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mariadb
  namespace: firefly-iii
spec:
  encryptedData:
    MYSQL_PASSWORD: AgAlMFv8R7YFjvGMP2v5EcYaUvP55m6g+qzLGVt/c+0DGbLpIdG86hdLejFFI5N1qrvCVdFg8Semfn1neOjukJ1tTtwCd1Lx3wWmrzsqgvS+JMKOGVJWUvGbG8dpuUzbQ8V3E4dNghSaVDeIJjY2jy0Fd5Qq34Apwk7RkMWkhe9V1SgFLXQUi3iR7eJ+4aJOCU5Xx4z+UPivzj4K+j+vub39+msDjaZXVvj9ipAl1japMG9h+YkM3l0HusPPV2SLCkFKRB5VBzSoPVvkhfteHHlytzE8hxa0uCAqHy2YkWroUABW+M3HB6jKpItsRBz1+wh3LozBp3yDGphB3tbGb4e5h+qizQBBu2XW10mj7mm+LKtMtWhvnhh5rkdekzmJMxvm1stmllUCObbtzs5N+zFZa2vTqn2EqRP+d5qMYHxdsIHmq0L6zMwgTjYIf/QbFyfevbD1kvSzxiEYiHwzJvrHxK5kjJbGVLr4MP2kzUTZCAlJisphB0NfGHfLkwAi8PlIGqoKQM39L1jHnwzmJXHJG3CBuHnHRj2VgjY0uEiMLb7feCtzyor8E5sAT9Xgndq8fUqmMsG6wNhx8T5Gi7iYRXsZHdtCXYkZg+9mjCSoiU9X5ioAQ0Ez1sXVV3ONdRyRZbncPC9pZFFW8ZzcuWylMDBuTy6oeU5/Xso9OZuE3yholXM4YutahfAzd3RM5tSg00QB+ayzK0zS
    MYSQL_ROOT_PASSWORD: AgBnFDY7JrZg3gnF0Lw4K2D/oODJVaR6kzTkCxricCV0ckJWZphJj/mKHWHvmMTE5OlbtGPoDVynPI+O3VRGaF0Bb8E0mvqVXMckSU87ZF+1dnMm1jBu48OZdoj2GFeLmHujIavydyi66PfeQb+vW5iogRoIEpP/qC0QyIGPbWV6N69HvAKxANj3tXFkpuliB5mE2E2+lhjw0y4DERhwDkdKWSsEHn+3HuMU40HwB3NduBanwVS3UC3MrJSkDMn5Je8hRDquaBDqoet6pRCuySUZYIHe5Hnoa8qfW0OO22M5qtV4mz+rMMoDfn8Vs1SJkFZ/aVtlsQ2S0Nn/nAl4snTbblparQ6y95oYnmxrU+4noLzjeeStm7TXpfK3Lxm1KKzsJqwwxKIzCx8xC3Awq2YTiGwQH6Nhr6LdSgOdHDWmka+zLYNECmza4T5NSA1icQv4SXI+uACvGoumBi0VjvbrblfyXr5x3YrXsaCIbv44LY0bR0FRrEX5rl05aEpa4WPSW5xb/WI36PjnU4bkNggHVNiYWCe0SKmDurAiDIzXEi7PL1+Z0iO/ioGjTRyvW9l6IkV/uJPSHRn0+FwyFZF29EomfX9bG4YJqGVfRIS6DJKl7UTShZ2gnYU8YXlF7NWG1cEkRKN/qsU87VfbJrMTNZnf70lyfSs3hGoe8EWKtAF4P3P/XksW+4qDzO6vpQdq6hHoSXqEBV7R
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mariadb
      namespace: firefly-iii
