---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflared
  namespace: cloudflared
spec:
  encryptedData:
    token: AgBHSN2oWnElWi8YvPE62/uPzty7IfAJoypxZ3mHZVUbs/aHP6roIjEH+bWkRyOL6s5n72CCLML2egk1UD0O1T57+V6hAY0g/zbefeUnBqACYqaDCEZu7GMS7kvaGqXq8oo3uyEeK157VdS38Qy4qZ59hR0K+aG98yPKgXgxq3K4FdBo5n3R2HpB89bl+Mdo76CLnJ+R++JqZuIz3SGrrSG7BlAPdtAomoqlC97a+L6p+COHPG1dRsjWNhF8b5o1+aTRicJtuBPAM0mQWwvdS7kizxdBQSsHnTq+zyh1DHtWxFg4IIl4Hxo7y2HpwOTkIieJQeMP85Zg5XUH7cLfR/2fERL+EudRLJvqClL7km2oL5gLD9K7lEtCuJFMdw3ybeNotXUmdWB6RfoH9F+sRDd2F9gnRNXi2WTD8KAenUX30rwhV3V7zu9FL4EfpTkuw6uwmYQJ5MtZjYM52MoGvY9pScfv8No/kqzSQUwnR8YOHN+PFVP21kjP3VcyaiYTi7eiMC8FXxALpNcIN0Hz1WGZyHRRpheRXvINQ/KpThzNZY70rO5odDka6hyAP5f//6+N1zzjHafRgA8aLnlNpZ1i/RBqplQGwtAMt0k7NxwYFmhmaViDZ3XEK5tq4XrAGBdz1zvfc9Lhq5pDg3O3l2fXKH/S02UZAnpRyaMKpEm4WPmp+/iUn82vq85iwp968D/eNyA3ACOqBM1T/3ddZLybX5top0K2i82xpDiRoLHKcWnumFCRgeFrJX2/tzS+pUgeN7l5GC9i2gsFSiW7H7J+7C4U6weBk/Hb2d15OK1RWI5P+1vllvrOxIUqWpB2EY0to9Chmn9YF+JqqIwBiCWytTOOHvciaZEXtbcx6xiOuY9MSG6DVWm4kdvM4Lfyj9MgvL68WsJBzVpo1bOoA829pYKzXb5L3QEx57s2oRArh/S2eeHFVRcS
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflared
      namespace: cloudflared
    type: Opaque
