kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: obsidian
  namespace: syncthing
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
