kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data1
  namespace: syncthing
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
