cronjob:
  schedule: '0 */6 * * *'
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1

resources:
  requests:
    cpu: 1000m
    memory: 2000Mi
  limits:
    memory: 2000Mi

envFrom:
  - secretRef:
      name: renovate-env

renovate:
  config: |
    {
      "platform": "github",
      "autodiscover": false,
      "printConfig": true,
      "repositories": ["AndreiGavriliu/homelab"],
      "gitAuthor": "RenovateBot <renovatebot@gavriliu.com>",
      "ignorePaths": [
        "archive/"
      ],
      "kubernetes": {
        "fileMatch": ["^clusters/hive/apps/[^/]+/k8s-manifests/.*\\.ya?ml$"]
      },
      "helm-values": {
        "fileMatch": ["^clusters/hive/apps/[^/]+/helm/values\\.ya?ml$"]
      },
      "argocd": {
        "fileMatch": ["^clusters/hive/argocd/.*\\.ya?ml$"]
      },
      "dependencyDashboard": true,
      "additionalBranchPrefix": "{{baseDir}}-",
      "packageRules": [
        {
          "matchPackageNames": ["lscr.io/linuxserver/calibre-web"],
          "allowedVersions": "!/^2021/"
        },
        {
          "matchPackageNames": ["lscr.io/linuxserver/calibre-web"],
          "allowedVersions": "<2"
        },
        {
          "matchPackageNames": ["influxdb"],
          "allowedVersions": "<2.0.0"
        },
        {
          "matchDatasources": ["docker"],
          "matchPackageNames": ["fireflyiii/core"],
          "versioning": "regex:^version-(?<major>\\d+)\\.(?<minor>\\d+)\\.(?<patch>\\d+)$"
        },
        {
          "matchDatasources": ["docker"],
          "matchPackageNames": ["fireflyiii/data-importer"],
          "versioning": "regex:^version-(?<major>\\d+)\\.(?<minor>\\d+)\\.(?<patch>\\d+)$"
        },
        {
          "matchManagers": ["helm-values"],
          "matchPaths": ["^clusters/hive/apps/[^/]+/helm/values\\.ya?ml$"],
          "updateTypes": ["minor", "patch"],
          "labels": ["helm-update", "minor-or-patch"]
        },
        {
          "matchManagers": ["helm-values"],
          "matchPaths": ["^clusters/hive/apps/[^/]+/helm/values\\.ya?ml$"],
          "updateTypes": ["major"],
          "labels": ["helm-update", "major"]
        },
        {
          "matchManagers": ["kubernetes"],
          "updateTypes": ["minor", "patch"],
          "labels": ["kubernetes-update", "minor-or-patch"]
        },
        {
          "matchManagers": ["kubernetes"],
          "updateTypes": ["major"],
          "labels": ["kubernetes-update", "major"]
        },
        {
          "matchManagers": ["argocd"],
          "updateTypes": ["minor", "patch"],
          "labels": ["argocd-update", "minor-or-patch"]
        },
        {
          "matchManagers": ["argocd"],
          "updateTypes": ["major"],
          "labels": ["argocd-update", "major"]
        },
        {
          "matchPaths": ["clusters/hive/apps/renovate/helm/values.yaml"],
          "automerge": true,
          "automergeType": "branch"
        }
      ]
    }