---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: alertmanager-to-github
  namespace: alertmanager-to-github
spec:
  encryptedData:
    ATG_GITHUB_TOKEN: AgB8peZD5SNrM5/yEvwjor4sxIjys613RxXat9N7zoU4P2aILx2587pEexoAop6JNYFEHfqlpYAWUrZZrTL3WrMgKMlE0pzpTZX+KW5PU5D208CrimvvpQwK0zCJZAIugORasheO9S79Rfek+jiodZQGbMnTtlU1l6z6pC2xiurl/WtYcku1ijBQJDYo9c82HK7n6DG2hi9A0q2YTetc/6fv+to8OQw/r6CTvN8yB9iijN2NCnzmg9RAsHz4f+LG0/phNTvvBCQX1y/uUNyGXdCBz0jF5WrbBMtHzBleW/9ggufR+bKAL2bmARv/72PDcFjJwbB4kXol3RMGTQTjVCHU+bDIOMkRT/5hbp8ph/apF3hSA434sZqq1JrFnLG2je/asY0NNpmdmrGJkhlR97CoYXrt6OuUv+bfTy1zR/HIz3/myZeOjvqa8rlkJcJf/L5TgunSSFJpRcLeKI9nt4RIpOkdBQK0hAW1b3RB6BuwEBoAWEYhcxPSqVseCbFhfq9yDtr9eURPa43N6XoUi3xf9kH+8HjaS/wuD/W2DECt3IHQgJcrND4ZLAgBHbDsRu2sC69u1oDIO/tCoAzHqEHjgdjouUD/eWkZJMiM0XqivplQTL0baVgqyjJVQeqN+p0chAET/P50RS6Dtf/GuuvD1RU6/nZ/npoRYD+22dZidXHeayJV1fues89/ESop+tWSLxobKlNg+jppNCUJZFMJWMNgFPPgnm28aGGqwcPeSVIoeHuTQ9n1
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: alertmanager-to-github
      namespace: alertmanager-to-github
