apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-media-files
  namespace: netbox
spec:
  # storageClassName: nfs-client
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
