controller:
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      memory: 100Mi

speaker:
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      memory: 100Mi
  frr:
    resources:
      requests:
        cpu: 50m
        memory: 200Mi
      limits:
        memory: 200Mi
  reloader:
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        memory: 100Mi
  frrMetrics:
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        memory: 100Mi