---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: renovate-env
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_GITHUB_COM_TOKEN: AgAwvlGF3c8xiANCRlm3S1EywAh87YM7kjTsK4JNP7HtM/3bs6WFXslxpdaqghKgnZIaLbPwuz+94C06/q6B9X7Ll1odpSM4AgJcHiJW98sbOLqXgy11rIcR4BPmrWGGGMQOPKNStGAk/Qen/2w8FGPbcNhUT3euzn00hCQR/vf/hw6SQNFQSmUVGMmqHWoWProFgt0uj31o8KZXGsOdKtNzJS6LXFOV5y8ItvJ/a6UvXvamav5LyT8a8DdhKI/uxBm9FypRfA9MgQugFXchd3XywOEij4R9HWvcPsGhPNssbtJIBaYHK9ggn8iYtKE4H9fM/H2lw+Y7ujG/Y9j78KzDx5YYy2Jn38FZKNo1GMAjsc4CqzumHafaXPWzs2btQRbZ4nYmMjBhqYAXGLZDMxAJEP12TocK3mmMDvl8zATWNG3WzudYgFhP8YIl8pcsBGalAgK6AQnrMI8npVLO7cSv5xwT0gx/219A5CCCjhq/Hw2amkcDaZuH21OXBQ17vZ/9fHdwiPcFVtE+HmlHbkyKyr95iM16ea/ewTYn5zjPK8RmgMfN5G3FyqfKh6nq+J4xX8LpjG397VoA03TvSei4aRbdt3H7GT4lp+CcFvDdRn7Mi9pyEPaHlTCTJYmEv9HKtVQH8tkCh/QXM0K+i182fLfP5znM8/RB0D5GbSb2kiY4g+IEedoS4PpDbxEgCIV2Ae+myfVFQC3Wvt7wqC3IrTYsvnl2jasLnLeW86zoZhrP4lssmuKZf/ZI6eqh0k1mLMVqa1kjcVFfjXqTNRbFKjm7i8Z30bZcErEKBS+cUNN/qjEKqq0Fvbl3Kz4=
    RENOVATE_PLATFORM: AgBqEtwDNB4xhxYPISp2moNhTQo0ROai/Q3iYAuCPEMTfgHZ7tpGLLSdTtbE55bz2Uv7xCnUm2RFHmjx4YSFmFU98XQ9Z8h1MuSyxrggPvJxUg1N24O98URCSwc7EH7TraWFpMvbXj6g6KU1Y/R4PCMfUh2LgYkr+vwo5UpXeikJSGpemq8N+/Qf5fqyk9Xlc7Gbdmv9yBfroEFH+wnFran5PVVej+2nDm40whgSDdp01UPIVKyEy63iLWOszYDxiR2m6vja4TFsAgh+dYtfTns/9srHhmIMeSgtN0cfWrYZty0tXKAoLkKT+7d7Tv/vdKFZqSbm+CJ9OXVfNrhTV3w5rHsDpoePfGF5evaXywwKvF+VSW8BPmfqa0TdyYXm2Y2M1Pv7QEGHe4RsrG1e5Nqe/M+QLMtFsNZimM7ogUHcIqFc5IOMMyv8ZmF0pUHT3ts0YNpl0yy+/rvm5PFOBsf862uEmM/zVLamKeXMetCeHgKLedR7pQUlVgGHjZNz9g2PYqKcYvZuwhA1di2vd/Fmg8KRlw/T3JoZ+O9cTT5gdegyQMvB6ZwwT0jGhSrIq9qBcm1zoB/tY3Kfiu/jupfEP+B1+Gk7E3j0X41fomYKLrgudezYqXq5W1mgr9BjiDZJQZ4rTV3l1xA4jnFriZ3iXLes4WFON2c8D7d8CFJdh0hjUIkLy2LL0KdK6uygLfvmHuEE/1E=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: renovate-env
      namespace: renovate
