---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: renovate
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_GITHUB_COM_TOKEN: AgAWB1vQawTlBm5w67hwwCUAsMzLlY+3Vp2PMOSQ7psA1nJYyHm8yT0wUuomJkbsSzmU81idEsTUaBbMBnUl7p+FFyTUd3TVNUUwTTc9rbHFpq6n0t9LgfoJE1fT24RySx7r0Paj4zjVQUzUWuQ89/CdUxHrH0wtbWrPAqnBjIw+QGbgLsN8AiNqoAtLI75VvKfqYmRFHrNnwRm4AGQjf8y8WkIxTKg5xCYQEbnmGFL71m7z5JcVmE6gQmLBEGB1cX8yRdwhPYmtJ+oCNQfh9+m2sqh5MIoemY4pxcWBlYGkF2fQzQfkBCURrojfGtphUSNbLRg58x8zOdbeRF5tFEh/LUJja1ECpMmQpPQMBc4KM7MDnBU31RAzDUh0L8ewvA9ntajywkV8FSmUwFWNbjGxZ4XrUDLpyoNPTAzgAZWqwPiPNSdaXlMv7TXM39D1VYxrs3rsNvSFapnkkO/ajlAj7BZsDAeskUJtPpZF32KmWtf9SUVl8cR8d0jkhLD8W1HM5R0AGWGpLe0qmc6MnXXb75GZ5rDYLCcb+jaWWNPbcGWe9UOVv/saF9Pt/ASYTshVpJhitHnFue/2A/aYrxWhnMyRSxqHP/YkvxeJsDk75z6S2YYpTNl5a8y9F5Hho0Vb/RT706THysXK4rrumDP/LS4Jh3HYT5aMS21qvEY9zROfUsCN2JPzFjW+Dt2erzphwv4QnJcm0HXvNtwWIeOz5C7435x8xGa4pjFBF+rTKuJLifsQ55K5VnY8TK679kWVhOKQJpwgh8Q/cyxnRnKETvCsHKU0wmnJoG8XFzYg/jfXvmbYIAgyCl9UHyc=
    RENOVATE_PLATFORM: AgA+Of5Ud/thppxGJbXcrT1jURy0K8lnp/S/DsROsso3tg4rhR6ue7581AYb6nZkTB9P2NhHLdeEq4gYwb0Gyxmqr5XrCEbUBMiRfIii43NeFhVPLNAj5+GcoimIPQ3FHXvXtQRLAWQFvBHO2NuYuSd3Zn4NADHLiy2TNKJgR3rcfGeiJ6XUTdN4m59efKw/nQ37Ie3pMed3pGgj2OyHE4fSKwp9nMRFHfZxIVv9wASx2igNQQVa4ebW6havWlwX/DGn4LRXKRo4RQ2i9wtIUf4CLkm7qXti9iEOcada0kyl7TMAdy/AWpIoSYig95DlCq7Gu7NWdIktr46UibJpEld3t1SkIGOHIzIe/fUtv6aTxwteEOP5NSo6WkENcWhvtS53G+1Zj8L5IdCVGCyhyZBYm2jEpWD59LSWgh2XqHTRbGTRHvP+f76qx/vZSq1zxrUUl+h8TNg0JNuSleT4gNI2K+11MdTZAbpS4zomk7H9ZZeGF4kgMD9lI5r9ZfVX1xBPqA8YCf75L+uvwOIqDdUY32W6leSSc2NUPW7p+THXb6TWdYP3sN96qr4fUwEKVQw9ilPmptY7JtgXoav5wNQDzWQudmeeQSssVRDGcCABTcLFXyUf4jpZmifDXq38I/GKf7wTfA0TsL6W4dQydvCZGQro6OnyeO4XL0boCsMccxFU0dlr04kPNfhXpFIDpo01uQemaaw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: renovate
      namespace: renovate
