---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: renovate
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_GITHUB_COM_TOKEN: AgAKMiGmsW8vpTjGBu95eUy9g7CBnNAhl81iI5dJOMrjWksYtAtlxHomcOYJqyMnYda2V+fexmCuZmnkqaVN+qTNi021s2JJdAURdrJGHE2qwY/IPMDqBrvFl4ubpPmzTosvrdUfl5nuxa4oa4JhpdzVcS/2Fb1tr9aEBNaGJ8kjSZti1STMI4IJ1nzW3MN+FVHGVRM435z2+G5Zt3ffxrjUXApyjkFxaM1QFidueCIdruqStMYDZSn26fXxU4VicZX3ohVvOwf+OeuTMLsvmJIYbHZ8kE+lOD5oFdMM/gbXWzloEMGO/Y60+4uacuow8WNTaIIjs0g9DrgvogCsfgwN32yW90R1IHiP/TTzHr+sY8w3ij3cdm+4P72MbMdZZt6EZmNlyOdieGrY2bOUUtttk/tTdJRKyyuZ8DSpSNICHNMJrqg3IXkGMg7HqUIz39HExlrOxKfhd+i6+qyoUk31V3YDwu4Y+xWSYGL5INROhh0q/UmD8/AU5NvCitIHQZ5wRxuYU91wr4Qbf61vWlSNNAS4WKQMzsU/QLQm1xJTE30jK5IWke/VbQFo/EbCWrYkylmtFGQdAbXmNNOmEbKW42txJMOgxiiatf+iJa872b5diEnnyhaD4u9OMXwrhOYuZf1O1ibgKsDyizkRBW1Nz0FasppMkNPNeKjxY8QWkDbgm2kyM65IP8+1JP91PFr/iu7m+BxoY9kD5I1gB6c/L1/PLCgL8qG7I31eqVJ4Vx8xyVsMtaHn
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: renovate
      namespace: renovate
