---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: renovate
  namespace: renovate
spec:
  encryptedData:
    GITHUB_COM_TOKEN: AgBL4NZkfRFcW/CMEfGkDkG7v+6/1L7YWQhTGMynn6W9eBMF0lVNIISjxQDmvd/Z5MFJtaJ/nMg5qVLxi2A849xw2IuULvXQk4IUKHAqpn58cxZGGZdexsaFrGGI9LV0qGyugqL1PjpLD8V8yiBWjd9e7VMNGND2G9XZvBxwwD4ZlEbx6DFtHy1FZx/9UqiFHY5Iq7kbWPAwybUVSutMhlxMHqlbVT5jM5QBrgs2OusEvAznpPFcRkzn1c0GV5Hp+AC66gqpDwhlPk4Ma6RwE+aySNcD5EmdHFI9lTZHFSWVEW1XH0pSXb7rXsodEoKQGZCwhbSo6BgcekG/W5yOWzCjXk564MwIgdP5HybGLdGETlys05DC7tdFNmjcBGqrsdbmnqXce0QmR7GlXPixfrBdw13r80TsP79BSw7j9j6tAuuy0CmagZOgxuhVh3i/MfvMvujAu7lQmmmBm85aksADm7fiAS6t/tTjOeGF+PWjdIgQokxR23PThlbeUulbqe5TraVGEaxWfBZ4gREt6yq3pWczd1gayRVcLvJriBE8NVvNy6N9HT60fkauEQtbR9EuFOnyd18TVzjOZMUQ3e6u7I84BE0AV4eKDw5aRGKCv5wRlWlRt4kUYInDB1i8xmsCyezlAvSXQg8RhekpevIFDcpzO7+DuvraP10Pg9zWsQgsMukfsia0P8t/6igqd8UI8iGNo5zgpsImHq+ByW2gI6o7UyXJw1XrpDV8yqeEW2yZRvI5ChaPYoobpVo8N/l7QWltaeX4AtVN2a89tuTL1cZwwqRBsMDZjTR45zZ2gort7uw0AzpPlvS8aAE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: renovate
      namespace: renovate
