---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: renovate
  namespace: renovate
spec:
  encryptedData:
    GITHUB_TOKEN: AgCSHJOGtzzGhYShzIAGBp4XuQm0kMr1AZ7JN8gSYvUPm57zpUuYwPlVeAAlWKjGsZkdbyeC0jAiREBJ/6B3OILbRv601LnCG0Fczyd2vB4rXwhX3BDSBJAVu9oLXQkGvxaLqmgy/hjoShoOznL7G2vqIntUieKjLI25JIRHwduQR/E35Of/grgTjQeFmfAe0sAUHWvD+4xm3kQUvCv9BFCxREN/5Cr+c6hc3HnJYsMCoEYR3kuPZ/Nm3/YJI97cfBbuuDXlHp2GjPUBhSvjAcgSJ96ySEjVyfpdf3RxCrav+nOl5gpsJ1RDL1BXUSBA0FzChjvnkJGCazRgHjQOWPR+QN9jtqZLJAl+qgs8C0Q8hQJrPKu9mHHzq+rQkTfq/A9OKqHDOoY1vLqArJd+99azbWR6RCmr5yVgfbPe8Ti1faqFRvK9S5ehAdtUJZ3XCf5MZ71iRgbletml/uKzJsxna5iWFHpFtR6RtSCDILtpC7cByvI04FItyBKnjC6sVPVfCPgw8VIbIVf/B9Ba4sIMhsBNUbQhjQn7K7xG3fA2+J/2c5wD+54XaHiMKQ3IzD37iZWbY9jqu9chV/wgwcFamHUVOYaAY9BeZ9ZIn34Qqkmo08yjQ8iJK5KSQv6dFaqyE5zZrrmEtB4aiRaHdQcZjDCBu6442fkzt1IcpvrWIXKuIJjVYaSuq9f/k+x5UDnrkZA57Xh8QKg7VzssREK7kQr9vnOPUs5sPrQNS040RWu95Nmt/7HyDG5lubNc4NH930wu97bq92sOAFsnNYnt+7cXsVqFQNwIVzgxlcHbMdo8Ll5+4kK7r55+mhw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: renovate
      namespace: renovate
