---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: renovate
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_GITHUB_COM_TOKEN: AgAsc67U+8yl9U38C7e3NvQnI6Y5QqbcLCHR3y4knPVDgibAhqPSenwxJCFBDomIqWaQBPbEuoPRuSYODLLXc+vCWmEWqwAM84yXDQYZPxuRHUq62VJuwtVoMEofv30zxbB+mO+wyw12pfrLfK1xBeUy6aZbPwHzJBMU8r554tk9vJsuid2t336CFHNz5h17DUovYxison/lLnS6B4QLBAh4fjVWdSyOR87ft9C7Zab/1IFQZfafrr3lYfGW1L5MtXTp/gHUqxyj1WNi3t+04/IdU3k834f7l+/AibUXrHIaOqsY2YVrEFPrTsXC0xq5unyxxFdM3Wq5/bgOWedNoDukfU4VV9QuILwjXXSfUdoH+QyEuI1V8RObb8CpIkAghFpm2gIz49cj4+mEAhGwrBJ6BB/9jAZDqfQsgP+Fg3ack2kf6IU1WmkTQF6qTI+INr1Fja+DzHTVyXnbUSyEo63H+U+1iaRh1txFMk85rMFMOH744pBKOqk+IMrQbabjATvdPWXBq6lam+TigieawQbKobSESMFf9a/THc8zy7xzZSUKzpq5+aB7+gx+8d1V/hp8kdvDJWPq4N4cbV8SXFZXX3k0wigDHUYx/7uLGuHzUXxAOXx64uIweN3LJauODoG+pHCF3WzCl1SOeQMKj++TY/pZ7crVQlWg4rQFcYpPiqLaed1/EBlp3KhPH4pR5rYJxl1rohjHp8N6rJCYCbeItKg5viquZeZ2XQrZiaxQujt2p/UskA9C+S06aAQfXTl9z52OAMcZ3JXscsJXFg7jjnYhgFBLztirCeVzAS2+lpyYbPOIKoDt/eg1pOM=
    RENOVATE_PLATFORM: AgAQDedOpvJMSOXdSdnusp1/cUy1s1xit43sj/uvlB19jac9IqnDkoSuOkEc6wTTJDu2bme+2b316krd4bMX+5WrXRZbekeiqJSver02XeXBAG0uV8iDKhsEk3wk0SSkQm1pzZySaDZyMB8NDdTfnptlyeUza5VGHZu2ytV0vhvc05z1Mws0Zx7059AhSeTSrODMCFTTKn30H2abp1Eev3hWW3fAwWKmdXu86rtBSPHy9CAQ0wnLNU0KXC5f/qIVS/IZUQ5w0NCMMNNlB4Sjh73X7TnKKcHVRguRZAawT1jcFqVyh7vpcPF3IakGKExOmXxyXMmGSs8uDr/Daz1nVOz4u2ICPLOCVPd/t3L+9DKOn26nm7eTsteMjnJg9ELWHQJVSN2mAyxSSEbTxErP2QYqRTOaLES15l1rk+XGdjuThqErvi9K1kUEPr1dktuG8Mw6riNXZ8jfiXqyDKT52J+LcXXMiJlIbXNYIRxwOp5dDBuX9amCrPftJVy4dZZUqPp9HL93vHVxIW/49dTzPsS8/+nKFiRsilgWJbmBXHBwshh5rup9AVIY1Kl2jFkTS6cymebc5N6w8q4G3uwkzXQTMvzqsdqGyzhnja2dfQtx7u/4zrMIHblw733c/hlJLfOamNo6q6ph+ZJp5vrCQtbgIXcLDNyf4ItB0K4BXIv+MAPoH4F9x58J/n25ZSPGvZaDyZVnWAs=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: renovate
      namespace: renovate
