---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: renovate
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_GITHUB_COM_TOKEN: AgBpey8NQ9Pk7qdNDjVzhO1lVbikRc+I4SE6An7fQl2JqjBKVvAICAcO3KhpXnGkg88O7SDzLg9+NVNo8vHzZMMXtGgjEE3V2LQYH/kXaWMZyrZsUTZFQCMHNpf5P03i3GlXu/tGU7XxwSCpJcOgepBvKPVWXpg/OT2dlf/iHx/7j9wdh+hSr4IvXMipmffeBbLb3/1JK8eB7rw2xUxsy49/CgW/rw9/75HeAjc8f5VU5YYREKqJRKH1JeDPv8frqFkZOqF5NKUAkJUl9tetbXKD5y+6hDu/Id1aqhy5la0zHyd1IhElOU9zy7Zj6SmW6+479wMQyAUnFq1wUiyEQoyfL/ZNYPDMtWZQowaFjqJQyNesGBzZ7uKcBiOuaSyRKGYBh9ctGz+kfKdpaldxqJ7ZEqcMql2KsL+3+eLpo17muu0TXhx+3zXR7uo59sUJpOPC/Qr3lsSq/xlWiQNt1W6E7LwesRJakCKigneJK1Z4T6ZdghDyuIB3gi/gMSqhwQcd0HlaCqbBBAN5qJXEjZMiWaGDFAbw3kPzeBh/ev3DQ3TIz8S+ACthDme6JLAjla70DAw0r5Sgg7nWKjNjpcU34L3xNZ3lnvMHhb5a8Fz1i2IbHRvW9QK/p31/KlyOERFTTX4bqY3bDHESiEO4AWMppXOSh9v7/h/PKnJed+URgObSSVhkLvGcsU1ABkV5HcxDWeWlEI8m+eH50eM5CHlOpEkvPySMF7/4+UyugFkFMRges1GbgeKR+8W2Hf763L4eKhrc3b9r6g7sJUAdOXpzp0GTMlBxOIyKuLTprwjoNvpe31XyCXYEpBi4cR3DPJ7NtD7TxGKqLIBbTLaaV5ofrr5M67Pis57J7lDI
    RENOVATE_PLATFORM: AgAUkHv6loilNoYsVWzg1WWUwfAL3unzY4ZgtuG3DHzRrCsg0FJhrFpiHd//qEB64tlBPah8+K9FbjxaOfV8psw4DYRHXXrkXX86gGw9mLkIn4GaHbcmGzte2Mk5/iQzAFRLzp2KhsdE7XB5l3KoJMKF2dgm1L0GMBTcgNdytY7kfAaWoFtr5FRRjbr6woe3LV0ENf11KF+SRU34QRC1k4v5XHXNhl44zxpOMu8UH0v93aHVteZBVEsITH+xFutbHc/859uhWI/hzf/dSiAO8aeVu8WWOFa8e9bjAMcMx/9JpGJjKOPEPJA6Lao48AyKlvURP5axuyXOzvu0Tt6RvD9p5yvLeZqZAFoX4EggvYsT9BDsMWyXskA4EXXNIj+C8HVaq5JDR2+T6s2z01jVCkyC/VRAVfJcHBZO5QT+9FaOzfTaF3BpFij5du/AnAr2KOfrCjn2ticcTw7E7qBNfK7VTfEa76iKNJkQ660bksPLsMKAY6woRPUEe0yGhx2LmMpW1o60qXSLBsbD19slGY68EsFisPQX7Z3DACIBjmmNOT7+j+ajfQ0hM1c/U4ZM6KcK0e8dz6YKQSC5JdvEvvBYSn+9SZU+XjVup2YTtPm5EbY1vEJN6JCxQeYcTtZpBIV446o+Y1hcRgc2wKlQkyTTYowx8szIr8HxZHdYJOsMmactswS2BMccnKW326ib7FD75Gcf7sw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: renovate
      namespace: renovate
    type: Opaque
