---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: renovate
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_GITHUB_COM_TOKEN: AgCXFY4Pj2rdSyn1RiRgotCwss7HsGpEOXXvSye+j6Enpan73MmF5fal8YBqgB+Xqgt4tZCO0CVYG5rk3NxE0elVGST7RHtZRW+ZNvIf+3TDMWFkZ7GbvJ/rhJY014StmgqA35dlbH5bn2TZWUekC34fvRbmVlfXcmfE7vA2voHGQFuNEcLi8A3j1S7zHBhzd6JIrS/xfUyb7MhCocz57LSJGX/ZRTomzpGJuPwPNyLHsKjGEUpdl2hcomqK2/SypkFarOn4rGB8G8/5SYJ/uyQQtCKfB080MDZD2jpFTE9Ovi0ZyNTUuegkM6vC48KkZIoOS+pVaeCOIt1uDMWIXBDteUfylYZ8HP8aZ1DIDOo4CY14EEmF3eNRmOpHV+eCtL4iF/CWsyb86mj65z09CdKcSFZ9pjhgKBT985ouh5Crw34FNHhwt3O5d9+LbcEe81RHtGcpPIjb1HhIlVu8+bd2PlPdGkc7IVUyDMF5myH1Y5MwtDhSqfXEzpGjJkiwpyrQCB60lkvHoMzitvipHNLYRdUN8M6r6C6T0XjvEpLtxH6Ug8agu4GAs9bz0MXzphJ/WjWRFSQnroq/ClUeJ3dDeyb1D+PaRxTUiExvmok/j0QvRHyepkuo6gvsQ4prmDvDrD3kuX1eCRzw5EldGWA1GV7HGZ17LPonWcVltRBknv+EJO7WqCd2gd9VLNAZeMLT2nzXavkCR3uqfj7/AVRM8VlGQIJop60rlthKcaX/tHxCyir+DM3eWBg34F5PaP7bG9fe5/EwK9IXV4eqaReF2p24yJbQCM6yIsuhPQ33mfFBtonPTgYVRH5l8DVK+0Rg3WSdgqqhvONTFz1uKv6/5xCiQeKz3UyPrT9b
    RENOVATE_PLATFORM: AgCL714d/0rnzST3d5QrzHBNSy6hUuKI+E03HkB+9MwpFG3L7NqdPtiby4k3H/iJxf38YuaO1INU/D+gS0pJSmU8iNfEkhXq+rSJmUdsdJ26yOsrq9AH5td0LCAlnVnKHgEiwvwoys23j6329uahlR9uD573Kcb8XrvggrV5Njw6xdtYDNoIkL52byzWvYhUztCfbyojG1VjH5GIVExcF0oSsS8hO1agp5bBVu0lNXrGC1mDk+RRwiH6TQNA9ui5GfCRsljhfOruMgwsq55OZqvrhZO2MrDOTYPiF10FGboAgl8E6aNuNIAOBVb2ss8RoC+UXJNau8ZJhwS+pgH1JC/nm45MtAbtPCMCJMyz4C5IRBgBV8/RjDyD0cr46iUbSUZIi1DbQ0W3Mg1oPV1wgWDj7VXP2NTTm2R51BYG2/fs62Qr+gFAfat4aZkiuBPrcLaujdx3tSrmNxuPWhMZe7X3V9UCuhBszDzuMWT+HU3HDqBs+xtdMVe4m1pT80u2XJUwoJCYuIghtvMFq8Z/kq8WcZ8OFSa4nmH4NEMTqHeqPmjoKOLVLgm2rh06w0RLzSrWWffADPQRQ6gYtmuyN4PSIsnGPlZvINQuBLabQKbMpQXdcD5eznxNMNzfjCD/0HY4RIdbfKlrCPEn2S0OilpSHXqb8bnnOm8ASrstfUhDwHElBmwk/TGy7lGUIIpQ8QriqjyXyZ8=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: renovate
      namespace: renovate
    type: Opaque
