---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: renovate
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_GITHUB_COM_TOKEN: AgBZHcSzAIvTrrrU8kExQn2US1Atqcldg/Pr9VxxSIm5IKIPCZjpH1QZWTJh71oFIZbFrGUbRKrgHqiDADimf+Zgc7drDiawoTaBaNPsFGI7FipHoJlgkDFhELdcgFKP2KNHjF07uc3ChxaJhWnJ58gS+FJl4lJ7B6Fm7jWrgVFRO3WMJfptoCOarlG4FQUlwxzwsIeHJv+7kVFndaCPyurC0UOGSGL6/ToRPQiT8L7hYcNyN2rwi/fH2ssVFnSMr5CSEwmwjz6M855BaDP1jpV0CrJ0QepGjQqduMRrfccu0kw6FIjpkOLQ1WHcrwnv4Vq2MMN5ZPajxCSNXei7EH77xPWovd3ydS9GJbbao+OFRuM2oFj+xDLe5cDT7c2DWvIomC+XUHxaquBbgHSa7lLMRq25l1kkivmZmNeoRxYLZyAdYcNDrQSanw3zQ1M/OV1mcBHzve9O4Z94FRJwEGGFmIXoWkdqk6FfPj/wSpuZXI299kn/BHySgtDVUwZireoTZu37xrQyswaDjNW8uCa7EtwvyRCWCEuG15YvhPkRa8xoG2DX6Xc6UukKScdlZ1lhilbAC+cOOHBD1MnaVrarHgoQwObaAeKVEvnU5PuqDFOuJgzkoIXXlZ0tZNQelpnpDYPC4IBmv/ZrDsoZ4j7TrHYxUt3cK8MubfLUQqE0kiqSx6K4Yzi5gnaGvEsxbO6OYYpAcw2U/XCrNjD10MpK3pNNEfnrB8NnZMSMp40iisdlA+iW0oQuFjeQytZWkHF8Bk+F4JBB4ISWRJksUw+uNviaI8XEJu8NKHOjV+um/cJPlq+7/JQVFBKIM3c=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: renovate
      namespace: renovate
