---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: renovate
  namespace: renovate
spec:
  encryptedData:
    GITHUB_TOKEN: AgCg9d7F2XjjMQhom2yx+BGwdPH9TZwG82RqUfuys7e+22FmHZD4yZOhvYs/AJ/YDE2R36sKl6TUjxTd6/DWi/14FZLx4/tJp5LUOevsQOcfl2RfE2AqsWXPRzDmBj6ZuP3TMG9aHCMx5yLlKp1ivvuqx/WdsAlMOeN2rt1D1IVuLtdjWJNiUZw9n1wdDuSVIByxOnbT/3HspP+fHnvEFxaE0/frtGpXQ0QSMyl4GKbYtfLGcvbRNNKyJtWC5frlr00tyuFKEsoIfuTuxHtwaT1XSDRmRBc7Gq9nzZeLjwhU/Jmc3LvtDgnDEGF2LtPZP3UgY4jhCMURUB+5iphuo1viJRrHkeRKiOPw08kFa1Q/Cp0akXXiOCTNDZ9ZyTDgef/t+e5wS7hSMb4ADWy7nEhBC5WSXHFs+9YFwsSIZx16wtr8NTuS6Sxt0uT+sd9Mr+ej2V3fct3ePVmpWNxTNQykGgpZzXgC2+ThQnkUSA0icSIyJF3N7DWVMST5iCWpyOFh1uX3Q+eKFX09jHlyP2g3SXTOq+Ze5jZJUxDkyoildiAn7zDHVAQp3R1uoJzSZOrf7aI4+ndaqIaLVjTkT7mYTXsR4VdoBNCNNLJ7mAgHDsVmw3A8vDvW14/oe+np/vt2V4N3yhZ0K5Ma7MLTKLmsHwMvvhMatTf2KCsW7TVn8IDJcLnSrEWNbg8NtdJmuULDKFR2zKBKM2gBeDE9ttrzX7v1cCqgL64ydIrlSJkGgUVZ5GayLrSTY0O01YsRXearFT1nqhC1NjqVt37maxaqoy3Lep7g/5ScGlc76WKlhszf3hBn7IjqLW3pQvM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: renovate
      namespace: renovate
