---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: renovate
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_GITHUB_COM_TOKEN: AgB3lq7Yk0T7tPVEzARvkUHG7BmJO5rcA152UZoqkX7/5T7kqDPn68XaSe3I5zs4Ix9GJJWRJeF+wrVM+EXxDcpAQRMmi3Dv+JuB72xaUfr/uy+lsbvbrIFDkHuaSUzh7e0f/IDiIs1dvScePFD/H5ivfKoCaGYtVNBS/TAGPKI9AXmLhEROlQumICY/7HwtkfALHqJYwF6kjjp6Sg7SQ+swdNbym23Ge+njwCig7MB/9GW4cLPXrg02dwM/bvU0tAcCqUXZH76c93xtNu3hMywxKtfskPmDBLxaCjzXJU5+Xw/LciTrW6lgu1yA8cKEQJUgoCcAtdMeTETgr2aXWcn/3o85tus43qojFVYhWz3F+vGGKGNIkMP6P3v2YHb9vDOGL0ec5ZvkJCESjO93jNfgEfK3Y0LcRhtYrJGo1Tzzg3Wo0TgNlojYcfA2oG/5iMnUwihrEB9lhDdA3ZSsapNH5+F9J4BuqDJSpBJPvo6GKHnvs8zeZJqtfa6mY+b0VFk743VAPkQETdUuhJ5rHcAXode1c89wCU+ynsWkyNGZkrlK19TMTdnPMJyul/EHL8bKJLQW/e84KTIK7hQG2peIgrcqUZC2+kshDxvbLWvqMNkn/yWzYV2rvhbRQZAw1fwYSD95z+8u9uDSFiJk01wa105nEp23mqbj/OQmpr8Lf7URlnLB/7f87nHbnh3F11H96Lh0u1Z/KIqbNU1lgSWCmxs5PalwaxIzFtziodCpDRwbvm2pEd84QC17G9/DKMPMwDvK96RojQdUj9L8Vb3Jt2243hlI0x1o/2C3EWr7CMMI0VQjLE6/Ljgj1u4=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: renovate
      namespace: renovate
