apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mariadb
  labels:
    k8s-app: mariadb
  namespace: dugulan-com
spec:
  minAvailable: 0
  selector:
    matchLabels:
      k8s-app: mariadb