---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mariadb
  namespace: dugulan-com
spec:
  encryptedData:
    MARIADB_PASSWORD: AgBwCDP5Pc4snWFyy3o8BkqcZiXmxg7NQ98b+dcScHG+0DFD/ZFA6IwryqVNV56q7Ay34FZLnqEVjrh36iC0N52fWVF31P5ZRSsj/iP7D3eE9PSPhy0l8LppAFdAJFWiJS+2seMtn9QTqSd40dI2IJLU8GcESaz1bulbBhslWCW5igC1kikLoOTdWTR6E2DzvPmcnm/0p8Oe2tzM38FciPW2NCMn+72JeuesKGkudd07HADFq7xicOoO4IE8fUChlc7YvLCsYB0ArqKLFigv9+fBfHuFVWOqEZVSwEqCFqDHl3FT8tsC3WtpQlrpOnQqMkVGpCAkssi0DFS6fVZYbezkERxV/59fIbigO4Nt1LeMyghd40V2qB/6raQL2ak04kK9TLHYWQ4+EfstkPhS8T5slqGuTrIf98HI1eLaASA1HYxLYwb16hS0lVFNZuhex8jAWgtAmvHUHC/O1A2N0NIdshXhduUNg1jUMZyDDU+bAcGnUS4Tj1nxGBSl5I3/aykPOHXGpinmXj6ayy8UhIhwbGJejEaQSS5p4ItjRojZL9wSKynHx1Jry94bckt684jiuH/7+Yt9adIziNEHOqVmbVafxu3w6B2acMqO0+2LahEY8ufI4xuFzvbSGlemFH4UbGlVy9VRtOiZkzuSQOVLiL88yaHgluuOm8AWji1+p6y2XiRi+hoZ5lNf/nPJ629guzYf/IfG3I8bDA/sZeeH3UhQeawLYnDWbz4dnjYfhQ==
    MARIADB_ROOT_PASSWORD: AgCK0HrIzcVqCn495mLKZLRlF/qv4NruSuPHFNKc1kbyyW70OcRiIhGiMLmk7q60beCZNxYPSgvGTFfoA8q0DhAEy6BkknuWfIYflxB49dDcNLkUUSnQpMNc23iO2IUCwYy01l3vktALMMaAOfsxAmilgItsBYQ4+EnPJtCtJH9Gv9dUWudr7D2FKdCclv1c1bzIUzaLq7a4y2l3F6yztGfsDtcHjooirjRclkPWD4YpoqHjik/GcnRXyovL/vKZCLezjgqdYVriZJZ0jEtDUHfyBXKrxKjTVlbs56SInOgZ74IVED6yC8OuXJD5mPA/hbCZxFeKVCCUvlpTfhzoyEwyEPL6TkubD3xO4xG94oU8mTcpd456Kft3epijMFuaje7aW/8M5EIbBItFIc8aSIaI5PqYpu2NSHzYg+osfup9gX+cXOTyxwoz2OK6v6VjwaQoegALKihK0Dgwxxw1DQmr86q/eCzFmWuC0h2P43OTFD8BJkyZCbQYgQPAXhuiM6ZziivsQ8yMTorYKUOPd+HjGivN3k6JFvIwX9EnWFGqXpUfyUZHheh/RROsZFETfE1icThMYMfg99doOcuj8qq2ZhyOtPQqBvy+oj6oIewxit8uCL/5amwAVtg7olXX4/OzmWg4dRu15sby2OloQrJ8FgANjN9EYNKoWoSUYRBQVSrKW1efHPhHJbpSJOsvW/wWgaeY5CrkcRI7rsKLwBm1IIxkU/Tkin3OegsfnRghvg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mariadb
      namespace: dugulan-com
    type: Opaque
